# Train Faster R-CNN, EfficientDet, RT-DETR

This notebook extends the YOLO comparison in `shrimp.ipynb` with three more detectors.

Fair-comparison rules used here:

- Same train/valid/test split as YOLO, exported from the same Roboflow project.
- Same image size: `512`.
- Same seeds: `0, 1, 2`.
- Same maximum epochs: `150`.
- Best checkpoint is selected by validation `mAP50-95`, not by train loss.
- Test split is evaluated only after checkpoint selection.
- Results are reported per run and as mean/std over seeds.

Use COCO JSON export for Faster R-CNN and EfficientDet, and YOLO export for RT-DETR through Ultralytics.

## Install Dependencies

In [1]:
!unzip /content/data.zip -d /content/data

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: /content/data/data/tom_benh.v1i.coco/train/76_jpg.rf.58a0a484913f3dd9495998301c327930.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._76_jpg.rf.58a0a484913f3dd9495998301c327930.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/26_jpg.rf.4ef707c555ca4b6199b13755358bbc9f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._26_jpg.rf.4ef707c555ca4b6199b13755358bbc9f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/88_jpg.rf.1fc77517a3e4c225ba2bc26669b6053d.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._88_jpg.rf.1fc77517a3e4c225ba2bc26669b6053d.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/58_jpg.rf.a4e9b93bcdbdd1904c83fafc1febc64c.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._58_jpg.rf.a4e9b93bcdbdd1904c83fafc1febc64c.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1217_jpg.rf.bbdacce1e5a7c369a8bbe847dd8ebe68.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1217_jpg.rf.bbdacce1e5a7c369a8bbe847dd8ebe68.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1054_jpg.rf.8fecef1e65ac60d1f310893346a41156.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1054_jpg.rf.8fecef1e65ac60d1f310893346a41156.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1418_jpg.rf.fa06d9cd41d215a5e92b24fc01cc377d.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1418_jpg.rf.fa06d9cd41d215a5e92b24fc01cc377d.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/7_jpg.rf.45a9fc9e7b9fdedb8bddf566e73eb6bc.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._7_jpg.rf.45a9fc9e7b9fdedb8bddf566e73eb6bc.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/10_jpg.rf.c27689eb2d772e2de2594de26e9ecba9.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._10_jpg.rf.c27689eb2d772e2de2594de26e9ecba9.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/694_jpg.rf.769f773227f1bf2dae875501ab65fe9b.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._694_jpg.rf.769f773227f1bf2dae875501ab65fe9b.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/286_jpg.rf.29714a32c843e8ecc653dfe2a3c43232.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._286_jpg.rf.29714a32c843e8ecc653dfe2a3c43232.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/817_jpg.rf.93650aae1dcd0fb718d9932795600de3.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._817_jpg.rf.93650aae1dcd0fb718d9932795600de3.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/2_jpg.rf.8eec2b5ac47ff44f0988f6d57a8d553b.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._2_jpg.rf.8eec2b5ac47ff44f0988f6d57a8d553b.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1437_jpg.rf.723476eebcbf540841243aae4b3ff7e2.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1437_jpg.rf.723476eebcbf540841243aae4b3ff7e2.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/551_jpg.rf.8d4409d36966fa798a3feae963fa0667.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._551_jpg.rf.8d4409d36966fa798a3feae963fa0667.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/103_jpg.rf.7ab5209d6758e06bdb6237693e2dd509.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._103_jpg.rf.7ab5209d6758e06bdb6237693e2dd509.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/867_jpg.rf.759ee93b45ff5c72a54adf702a3f3e88.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._867_jpg.rf.759ee93b45ff5c72a54adf702a3f3e88.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/104_jpg.rf.b1b4412c9fff37b8705ac8d5cdafd05a.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._104_jpg.rf.b1b4412c9fff37b8705ac8d5cdafd05a.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1385_jpg.rf.a8e4f799828c273fb0a27d1337d784bc.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1385_jpg.rf.a8e4f799828c273fb0a27d1337d784bc.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/958_jpg.rf.77159624372ec78c76b686a0bec4deca.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._958_jpg.rf.77159624372ec78c76b686a0bec4deca.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/422_jpg.rf.8e6b5051fa5f63c25c6c1f1e1da6cafa.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._422_jpg.rf.8e6b5051fa5f63c25c6c1f1e1da6cafa.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1193_jpg.rf.f4c57d29e2f70fdfe0bf63a8ccb2befd.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1193_jpg.rf.f4c57d29e2f70fdfe0bf63a8ccb2befd.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/929_jpg.rf.e92bfc09a5ae02c4f28c5d0f9c830a71.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._929_jpg.rf.e92bfc09a5ae02c4f28c5d0f9c830a71.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/116_jpg.rf.a28538ff1233131eb6f122ce66943fa6.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._116_jpg.rf.a28538ff1233131eb6f122ce66943fa6.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/772_jpg.rf.a5e5ed8c7f8a18f1792cbf31ebd396e2.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._772_jpg.rf.a5e5ed8c7f8a18f1792cbf31ebd396e2.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/221_jpg.rf.a0f1b90a54d9f082f74619a6c72c5013.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._221_jpg.rf.a0f1b90a54d9f082f74619a6c72c5013.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1504_jpg.rf.904f18540eb6840660f536b53cae2188.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1504_jpg.rf.904f18540eb6840660f536b53cae2188.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/487_jpg.rf.faa31a7cf03d0e5e6cdfe8e1c1dc88de.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._487_jpg.rf.faa31a7cf03d0e5e6cdfe8e1c1dc88de.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/877_jpg.rf.26ab47c9102858ff5e1cc4459074d39c.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._877_jpg.rf.26ab47c9102858ff5e1cc4459074d39c.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/641_jpg.rf.440947755c5487d01fd2a4eec865b266.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._641_jpg.rf.440947755c5487d01fd2a4eec865b266.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/713_jpg.rf.86cb3d81184696864fb6b170dd2278ff.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._713_jpg.rf.86cb3d81184696864fb6b170dd2278ff.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1091_jpg.rf.b886b93ce0fc0833c34cbe12ec4f7d6f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1091_jpg.rf.b886b93ce0fc0833c34cbe12ec4f7d6f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1386_jpg.rf.23ad03f65ba0871e43fe42f9630ef8d1.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1386_jpg.rf.23ad03f65ba0871e43fe42f9630ef8d1.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1016_jpg.rf.1e815f6102e5fa5b36c22665a88d78c3.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1016_jpg.rf.1e815f6102e5fa5b36c22665a88d78c3.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1296_jpg.rf.e1c51d746438ba0e683b6125765a9a44.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1296_jpg.rf.e1c51d746438ba0e683b6125765a9a44.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1428_jpg.rf.370fa9c8a714906cebd34eed61ebbd29.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1428_jpg.rf.370fa9c8a714906cebd34eed61ebbd29.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1310_jpg.rf.bec675cc1ec91e51787254fafd200f4a.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1310_jpg.rf.bec675cc1ec91e51787254fafd200f4a.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/481_jpg.rf.5e524b7911f0497f2c8e7c5c9252c8d2.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._481_jpg.rf.5e524b7911f0497f2c8e7c5c9252c8d2.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/48_jpg.rf.13e682a2bc298c5c96c83b4b2e2c9ccb.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._48_jpg.rf.13e682a2bc298c5c96c83b4b2e2c9ccb.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1163_jpg.rf.bbab166249b312324f0b08e0c4bbb062.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1163_jpg.rf.bbab166249b312324f0b08e0c4bbb062.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/777_jpg.rf.459648d7236f9efcd7e21bb7738c89b8.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._777_jpg.rf.459648d7236f9efcd7e21bb7738c89b8.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/469_jpg.rf.c4b6e37c8b40e2859cff1e21b79007a1.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._469_jpg.rf.c4b6e37c8b40e2859cff1e21b79007a1.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1392_jpg.rf.1ed3ed05eea93e10f5a1d62c97126123.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1392_jpg.rf.1ed3ed05eea93e10f5a1d62c97126123.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/117_jpg.rf.c3ac5800deb00d2f53555e3bcfa83235.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._117_jpg.rf.c3ac5800deb00d2f53555e3bcfa83235.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/473_jpg.rf.b3b0cf0e8c7926d57808960c2cec38c1.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._473_jpg.rf.b3b0cf0e8c7926d57808960c2cec38c1.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1137_jpg.rf.b42346865ac11033eca8c23291305b0f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1137_jpg.rf.b42346865ac11033eca8c23291305b0f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1120_jpg.rf.460856edfb2d7e675652d3d9082e9131.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1120_jpg.rf.460856edfb2d7e675652d3d9082e9131.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/310_jpg.rf.605b5e735043cfd1bb16f8d512d580ac.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._310_jpg.rf.605b5e735043cfd1bb16f8d512d580ac.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1027_jpg.rf.eeeeb758527873a6d0bcdda15ebf28d7.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1027_jpg.rf.eeeeb758527873a6d0bcdda15ebf28d7.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/235_jpg.rf.afccfb7c5991513cfc86ac2d77cf1026.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._235_jpg.rf.afccfb7c5991513cfc86ac2d77cf1026.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/182_jpg.rf.54c5d77e57287b8ee7791e030d2cf69f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._182_jpg.rf.54c5d77e57287b8ee7791e030d2cf69f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1165_jpg.rf.f36099db9b9833386eba621f3c4d5136.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1165_jpg.rf.f36099db9b9833386eba621f3c4d5136.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1352_jpg.rf.b24b2361cd931f7d99b62f426a5e1f74.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1352_jpg.rf.b24b2361cd931f7d99b62f426a5e1f74.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/444_jpg.rf.2ab9f04af6e2a0b25c23060aca0b667d.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._444_jpg.rf.2ab9f04af6e2a0b25c23060aca0b667d.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/583_jpg.rf.a5fc084ecf8b97ebf8a20d006bb459bb.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._583_jpg.rf.a5fc084ecf8b97ebf8a20d006bb459bb.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1435_jpg.rf.4c5ed93fe64adf250135738e6160316f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1435_jpg.rf.4c5ed93fe64adf250135738e6160316f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/639_jpg.rf.4459e82c60e4830f1ae8236f4f00f8c5.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._639_jpg.rf.4459e82c60e4830f1ae8236f4f00f8c5.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/933_jpg.rf.ae236d125289bbed8493e75667ab51ee.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._933_jpg.rf.ae236d125289bbed8493e75667ab51ee.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/946_jpg.rf.447b50a3a727b36bf27c03dec45413e5.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._946_jpg.rf.447b50a3a727b36bf27c03dec45413e5.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1379_jpg.rf.57792e593861bf43e7d717442251939a.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1379_jpg.rf.57792e593861bf43e7d717442251939a.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/574_jpg.rf.b854eff996a7ded407680a408970dfed.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._574_jpg.rf.b854eff996a7ded407680a408970dfed.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1037_jpg.rf.d8012f0bb327d13d6f48e763b517fd52.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1037_jpg.rf.d8012f0bb327d13d6f48e763b517fd52.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1438_jpg.rf.50708f984b50520a81fd337d802f1725.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1438_jpg.rf.50708f984b50520a81fd337d802f1725.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/200_jpg.rf.12f5eaaf93b065c17308ec1392ecf6c2.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._200_jpg.rf.12f5eaaf93b065c17308ec1392ecf6c2.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/556_jpg.rf.f9bfae426236efa8cd342a27b7e67623.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._556_jpg.rf.f9bfae426236efa8cd342a27b7e67623.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/482_jpg.rf.5cdc47b42bbff2acfd185c8b6a5d29b1.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._482_jpg.rf.5cdc47b42bbff2acfd185c8b6a5d29b1.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/904_jpg.rf.dd39b5bb820fce4d485e33ed3fbd79d4.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._904_jpg.rf.dd39b5bb820fce4d485e33ed3fbd79d4.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/515_jpg.rf.5b8c34b376d9ed140c2f204235c79af7.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._515_jpg.rf.5b8c34b376d9ed140c2f204235c79af7.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/253_jpg.rf.a9c997b961d11dcde3bef4abe2339fc5.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._253_jpg.rf.a9c997b961d11dcde3bef4abe2339fc5.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/594_jpg.rf.68bc0d78f332650d478df45c4a500310.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._594_jpg.rf.68bc0d78f332650d478df45c4a500310.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/302_jpg.rf.776a1f0ba16bca5ba3a2e832224b2cb9.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._302_jpg.rf.776a1f0ba16bca5ba3a2e832224b2cb9.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/360_jpg.rf.438740ced8cfc4641714243c6f729fa5.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._360_jpg.rf.438740ced8cfc4641714243c6f729fa5.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1150_jpg.rf.094bff8a665334f215bd541adaa2be2d.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1150_jpg.rf.094bff8a665334f215bd541adaa2be2d.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1307_jpg.rf.d89a3f914239e6dde2d78fe54759f1a8.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1307_jpg.rf.d89a3f914239e6dde2d78fe54759f1a8.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/903_jpg.rf.66004643d23215d4e49edd156511f65b.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._903_jpg.rf.66004643d23215d4e49edd156511f65b.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/160_jpg.rf.20875a2a1770c9f65056818a1bd2ceaf.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._160_jpg.rf.20875a2a1770c9f65056818a1bd2ceaf.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/822_jpg.rf.6774cbd65647b4b6449db762f7b06d55.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._822_jpg.rf.6774cbd65647b4b6449db762f7b06d55.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/745_jpg.rf.4677aa2ff590b21c0c5d250c1463dc43.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._745_jpg.rf.4677aa2ff590b21c0c5d250c1463dc43.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/869_jpg.rf.fe56992d8f595168526ca2d59d41073f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._869_jpg.rf.fe56992d8f595168526ca2d59d41073f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/101_jpg.rf.0a19a8309c71b3046e08a42783e1a934.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._101_jpg.rf.0a19a8309c71b3046e08a42783e1a934.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/191_jpg.rf.17e8eb567f9da50beaf3726c353dede9.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._191_jpg.rf.17e8eb567f9da50beaf3726c353dede9.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/27_jpg.rf.04e75fe7e0ed27ecd86f715b4c53b29f.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._27_jpg.rf.04e75fe7e0ed27ecd86f715b4c53b29f.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1499_jpg.rf.4345aff10fae8a373ba40f91fcff7407.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1499_jpg.rf.4345aff10fae8a373ba40f91fcff7407.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/652_jpg.rf.f08507988260bf25ed77b9e967d06fb9.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._652_jpg.rf.f08507988260bf25ed77b9e967d06fb9.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/616_jpg.rf.6a7e17fc8f7ba5d04241906963721112.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._616_jpg.rf.6a7e17fc8f7ba5d04241906963721112.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1067_jpg.rf.7f4f0911ab36d74815daa91c0f4e3eea.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1067_jpg.rf.7f4f0911ab36d74815daa91c0f4e3eea.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/236_jpg.rf.bf56f88bfd369501ed93ccf6fe454c84.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._236_jpg.rf.bf56f88bfd369501ed93ccf6fe454c84.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/129_jpg.rf.cea7ecd91bb611dece354e3044f27a56.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._129_jpg.rf.cea7ecd91bb611dece354e3044f27a56.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/218_jpg.rf.cc9995ad56ba8c79c803e9753983b837.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._218_jpg.rf.cc9995ad56ba8c79c803e9753983b837.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1431_jpg.rf.180935cbbc952c6ef682a80b304339cd.jpg
  inflating: /content/data/__MACOSX/data/tom_benh.v1i.coco/train/._1431_jpg.rf.180935cbbc952c6ef682a80b304339cd.jpg
  inflating: /content/data/data/tom_benh.v1i.coco/train/1151_jpg.rf.1a1aa776777055a601082e5b31c814ba.jpg

In [2]:
!pip install -q ultralytics effdet pycocotools torchmetrics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 68.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.5/112.5 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 70.9 MB/s eta 0:00:00

## Configuration

In [8]:
from pathlib import Path
from typing import Optional
import json
import math
import random
import time

import numpy as np
import pandas as pd
from PIL import Image

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision.transforms import functional as TF
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection import FasterRCNN_ResNet50_FPN_V2_Weights
from torchvision.ops import box_iou
from pycocotools.coco import COCO
from torchmetrics.detection.mean_ap import MeanAveragePrecision

from pathlib import Path

# Thư mục dữ liệu gốc sau khi giải nén
DATA_ROOT = Path('/content/data/data')

# COCO JSON export dùng cho Faster R-CNN và EfficientDet
COCO_ROOT = DATA_ROOT / 'tom_benh.v1i.coco'

COCO_TRAIN_JSON = COCO_ROOT / 'train' / '_annotations.coco.json'
COCO_VAL_JSON = COCO_ROOT / 'valid' / '_annotations.coco.json'
COCO_TEST_JSON = COCO_ROOT / 'test' / '_annotations.coco.json'

# YOLOv11 export dùng cho RT-DETR thông qua Ultralytics
YOLO_ROOT = DATA_ROOT / 'tom_benh.v1i.yolov11'
YOLO_DATA_YAML = YOLO_ROOT / 'data.yaml'

# Thư mục lưu kết quả huấn luyện trên Google Drive
OUTPUT_ROOT = Path('/content/drive/MyDrive/shrimp/runs_detection_models')
YOLO_RUNS_ROOT = Path('/content/drive/MyDrive/shrimp/runs')
YOLO_SUMMARY_PER_RUN = Path(
    '/content/drive/MyDrive/shrimp/test_summary_per_run.csv'
)
IMG_SIZE = 512
EPOCHS = 150
PATIENCE = 20
SEEDS = [0, 1, 2]

# YOLO was trained with batch=32. The custom PyTorch detectors usually cannot fit
# batch=32 on a Colab T4, so we use gradient accumulation to keep an effective
# batch size close to YOLO for optimization.
BATCH_SIZE = 4
EFFECTIVE_BATCH_SIZE = 32
ACCUM_STEPS = max(1, math.ceil(EFFECTIVE_BATCH_SIZE / BATCH_SIZE))

NUM_WORKERS = 2
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
SCORE_THRESHOLD = 0.001

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

print('device:', DEVICE)
print('coco root:', COCO_ROOT)
print('yolo data yaml:', YOLO_DATA_YAML)
print('output root:', OUTPUT_ROOT)
print('img size:', IMG_SIZE)
print('epochs:', EPOCHS)
print('patience:', PATIENCE)
print('batch size:', BATCH_SIZE)
print('effective batch size:', BATCH_SIZE * ACCUM_STEPS)
print('accum steps:', ACCUM_STEPS)

device: cuda
coco root: /content/data/data/tom_benh.v1i.coco
yolo data yaml: /content/data/data/tom_benh.v1i.yolov11/data.yaml
output root: /content/drive/MyDrive/shrimp/runs_detection_models
img size: 512
epochs: 150
patience: 20
batch size: 4
effective batch size: 32
accum steps: 8

In [9]:
paths_to_check = {
    'COCO train JSON': COCO_TRAIN_JSON,
    'COCO validation JSON': COCO_VAL_JSON,
    'COCO test JSON': COCO_TEST_JSON,
    'YOLO data.yaml': YOLO_DATA_YAML,
}

for name, path in paths_to_check.items():
    print(f'{name}:')
    print(f'  Path: {path}')
    print(f'  Exists: {path.exists()}')

COCO train JSON:
  Path: /content/data/data/tom_benh.v1i.coco/train/_annotations.coco.json
  Exists: True
COCO validation JSON:
  Path: /content/data/data/tom_benh.v1i.coco/valid/_annotations.coco.json
  Exists: True
COCO test JSON:
  Path: /content/data/data/tom_benh.v1i.coco/test/_annotations.coco.json
  Exists: True
YOLO data.yaml:
  Path: /content/data/data/tom_benh.v1i.yolov11/data.yaml
  Exists: True

## Dataset And Reproducibility Utilities

In [10]:
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def require_files(paths):
    missing = [str(p) for p in paths if not Path(p).exists()]
    if missing:
        message = 'Missing required dataset files:' + chr(10) + chr(10).join(missing)
        raise FileNotFoundError(message)


def letterbox_image_and_boxes(image: Image.Image, boxes_xywh, img_size: int):
    """YOLO-style letterbox resize that preserves aspect ratio."""
    orig_w, orig_h = image.size
    scale = min(img_size / orig_w, img_size / orig_h)
    new_w = int(round(orig_w * scale))
    new_h = int(round(orig_h * scale))
    pad_x = (img_size - new_w) / 2.0
    pad_y = (img_size - new_h) / 2.0

    resized = image.resize((new_w, new_h), Image.BILINEAR)
    canvas = Image.new('RGB', (img_size, img_size), (114, 114, 114))
    canvas.paste(resized, (int(round(pad_x)), int(round(pad_y))))

    boxes = []
    for x, y, w, h in boxes_xywh:
        x1 = x * scale + pad_x
        y1 = y * scale + pad_y
        x2 = (x + w) * scale + pad_x
        y2 = (y + h) * scale + pad_y
        x1 = max(0.0, min(float(img_size - 1), x1))
        y1 = max(0.0, min(float(img_size - 1), y1))
        x2 = max(0.0, min(float(img_size - 1), x2))
        y2 = max(0.0, min(float(img_size - 1), y2))
        boxes.append([x1, y1, x2, y2])
    return canvas, boxes


class CocoDetectionDataset(Dataset):
    def __init__(self, annotation_file: Path, img_size: int = 512, effdet_targets: bool = False):
        self.annotation_file = Path(annotation_file)
        self.image_dir = self.annotation_file.parent
        self.img_size = img_size
        self.effdet_targets = effdet_targets
        self.coco = COCO(str(self.annotation_file))
        self.image_ids = sorted(self.coco.getImgIds())
        self.cat_ids = sorted(self.coco.getCatIds())
        self.cat_id_to_label = {cat_id: idx + 1 for idx, cat_id in enumerate(self.cat_ids)}
        self.label_to_cat_id = {label: cat_id for cat_id, label in self.cat_id_to_label.items()}
        self.class_names = [self.coco.cats[cat_id]['name'] for cat_id in self.cat_ids]

    def __len__(self):
        return len(self.image_ids)

    def __getitem__(self, idx):
        image_id = self.image_ids[idx]
        image_info = self.coco.loadImgs(image_id)[0]
        image_path = self.image_dir / image_info['file_name']
        image = Image.open(image_path).convert('RGB')

        ann_ids = self.coco.getAnnIds(imgIds=image_id, iscrowd=None)
        anns = self.coco.loadAnns(ann_ids)

        raw_boxes = []
        labels = []
        iscrowd = []
        for ann in anns:
            x, y, w, h = ann['bbox']
            if w <= 0 or h <= 0:
                continue
            raw_boxes.append([x, y, w, h])
            labels.append(self.cat_id_to_label[ann['category_id']])
            iscrowd.append(int(ann.get('iscrowd', 0)))

        image, boxes = letterbox_image_and_boxes(image, raw_boxes, self.img_size)
        valid_boxes = []
        valid_labels = []
        valid_iscrowd = []
        areas = []
        for box, label, crowd in zip(boxes, labels, iscrowd):
            x1, y1, x2, y2 = box
            if x2 <= x1 or y2 <= y1:
                continue
            valid_boxes.append(box)
            valid_labels.append(label)
            valid_iscrowd.append(crowd)
            areas.append((x2 - x1) * (y2 - y1))

        image_tensor = TF.to_tensor(image)
        boxes_tensor = torch.tensor(valid_boxes, dtype=torch.float32).reshape(-1, 4)
        labels_tensor = torch.tensor(valid_labels, dtype=torch.int64)

        target = {
            'boxes': boxes_tensor,
            'labels': labels_tensor,
            'image_id': torch.tensor([image_id], dtype=torch.int64),
            'area': torch.tensor(areas, dtype=torch.float32),
            'iscrowd': torch.tensor(valid_iscrowd, dtype=torch.int64),
        }

        if not self.effdet_targets:
            return image_tensor, target

        # effdet training uses yxyx boxes and one-based class ids; -1 pads ignored boxes.
        boxes_yxyx = boxes_tensor[:, [1, 0, 3, 2]] if len(boxes_tensor) else torch.zeros((0, 4), dtype=torch.float32)
        return image_tensor, {'bbox': boxes_yxyx, 'cls': labels_tensor}


def detection_collate(batch):
    return tuple(zip(*batch))


def efficientdet_collate(batch):
    images, targets = zip(*batch)
    images = torch.stack(images, dim=0)

    max_boxes = max(t['bbox'].shape[0] for t in targets)
    max_boxes = max(max_boxes, 1)

    bbox = torch.zeros((len(targets), max_boxes, 4), dtype=torch.float32)
    cls = torch.full((len(targets), max_boxes), -1, dtype=torch.int64)
    img_scale = torch.ones((len(targets),), dtype=torch.float32)
    img_size = torch.full((len(targets), 2), IMG_SIZE, dtype=torch.float32)

    for i, t in enumerate(targets):
        n = t['bbox'].shape[0]
        if n:
            bbox[i, :n] = t['bbox']
            cls[i, :n] = t['cls']

    return images, {'bbox': bbox, 'cls': cls, 'img_scale': img_scale, 'img_size': img_size}


def make_detection_loader(ds, batch_size: int, shuffle: bool, seed: Optional[int] = None):
    generator = None
    if seed is not None:
        generator = torch.Generator()
        generator.manual_seed(seed)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        collate_fn=detection_collate,
        generator=generator,
    )


def make_effdet_loader(ds, batch_size: int, shuffle: bool, seed: Optional[int] = None):
    generator = None
    if seed is not None:
        generator = torch.Generator()
        generator.manual_seed(seed)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        collate_fn=efficientdet_collate,
        generator=generator,
    )


require_files([COCO_TRAIN_JSON, COCO_VAL_JSON, COCO_TEST_JSON, YOLO_DATA_YAML])

train_ds = CocoDetectionDataset(COCO_TRAIN_JSON, IMG_SIZE)
val_ds = CocoDetectionDataset(COCO_VAL_JSON, IMG_SIZE)
test_ds = CocoDetectionDataset(COCO_TEST_JSON, IMG_SIZE)

eff_train_ds = CocoDetectionDataset(COCO_TRAIN_JSON, IMG_SIZE, effdet_targets=True)

CLASS_NAMES = train_ds.class_names
NUM_CLASSES = len(CLASS_NAMES)

print('classes:', CLASS_NAMES)
print('num classes:', NUM_CLASSES)
print('train images:', len(train_ds), 'val images:', len(val_ds), 'test images:', len(test_ds))

loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
classes: ['shrimp', '0', '1']
num classes: 3
train images: 707 val images: 202 test images: 101

## Shared Evaluation Helpers

In [11]:
def new_pr_counts():
    return {'tp': 0, 'fp': 0, 'fn': 0}


def update_pr_counts(preds, targets, counts, iou_threshold=0.5):
    for pred, target in zip(preds, targets):
        pred_boxes = pred['boxes']
        pred_scores = pred['scores']
        pred_labels = pred['labels']
        target_boxes = target['boxes']
        target_labels = target['labels']

        if len(pred_boxes):
            order = torch.argsort(pred_scores, descending=True)
            pred_boxes = pred_boxes[order]
            pred_labels = pred_labels[order]

        matched_targets = set()
        for p_box, p_label in zip(pred_boxes, pred_labels):
            candidate_idx = [
                i for i, t_label in enumerate(target_labels)
                if i not in matched_targets and int(t_label) == int(p_label)
            ]
            if not candidate_idx:
                counts['fp'] += 1
                continue

            candidate_boxes = target_boxes[candidate_idx]
            ious = box_iou(p_box.reshape(1, 4), candidate_boxes).reshape(-1)
            best_pos = int(torch.argmax(ious).item())
            if float(ious[best_pos]) >= iou_threshold:
                counts['tp'] += 1
                matched_targets.add(candidate_idx[best_pos])
            else:
                counts['fp'] += 1

        counts['fn'] += max(0, len(target_boxes) - len(matched_targets))


def precision_recall_from_counts(counts):
    tp, fp, fn = counts['tp'], counts['fp'], counts['fn']
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    return precision, recall


def metric_to_row(metric_result: dict, pr_counts: dict):
    precision, recall = precision_recall_from_counts(pr_counts)
    return {
        'precision': float(precision),
        'recall': float(recall),
        'mAP50': float(metric_result['map_50'].item()),
        'mAP50-95': float(metric_result['map'].item()),
    }


@torch.no_grad()
def evaluate_torchvision_detector(model, data_loader, device=DEVICE, score_threshold=SCORE_THRESHOLD):
    model.eval()
    metric = MeanAveragePrecision(box_format='xyxy', iou_type='bbox')
    pr_counts = new_pr_counts()
    total_infer_ms = []

    for images, targets in data_loader:
        images = [img.to(device) for img in images]
        metric_targets = [
            {'boxes': t['boxes'].cpu(), 'labels': t['labels'].cpu()}
            for t in targets
        ]

        if device == 'cuda':
            torch.cuda.synchronize()
        t0 = time.perf_counter()
        outputs = model(images)
        if device == 'cuda':
            torch.cuda.synchronize()
        total_infer_ms.append((time.perf_counter() - t0) * 1000.0 / max(1, len(images)))

        preds = []
        for out in outputs:
            scores = out['scores'].detach().cpu()
            keep = scores >= score_threshold
            preds.append({
                'boxes': out['boxes'].detach().cpu()[keep],
                'scores': scores[keep],
                'labels': out['labels'].detach().cpu()[keep],
            })
        metric.update(preds, metric_targets)
        update_pr_counts(preds, metric_targets, pr_counts, iou_threshold=0.5)

    result = metric.compute()
    row = metric_to_row(result, pr_counts)
    row['inference_ms'] = float(np.mean(total_infer_ms)) if total_infer_ms else np.nan
    return row


def save_json(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding='utf-8')


def save_run_result(run_dir: Path, row: dict):
    pd.DataFrame([row]).to_csv(run_dir / 'test_metrics.csv', index=False)
    save_json(run_dir / 'test_metrics.json', row)


def summarize_results(rows, output_root=OUTPUT_ROOT):
    df_runs = pd.DataFrame(rows)
    per_run_path = output_root / 'detection_models_test_summary_per_run.csv'
    summary_path = output_root / 'detection_models_test_summary_mean_std.csv'
    df_runs.to_csv(per_run_path, index=False)

    metric_cols = [
        'precision', 'recall', 'mAP50', 'mAP50-95',
        'inference_ms', 'best_epoch', 'best_val_mAP50-95'
    ]
    metric_cols = [c for c in metric_cols if c in df_runs.columns]
    df_summary = df_runs.groupby('model')[metric_cols].agg(['mean', 'std'])
    df_summary.columns = [f'{col}_{stat}' for col, stat in df_summary.columns]
    df_summary = df_summary.reset_index()
    df_summary.to_csv(summary_path, index=False)

    print('per-run saved:', per_run_path)
    print('summary saved:', summary_path)
    display(df_runs)
    display(df_summary)
    return df_runs, df_summary

## Faster R-CNN Training And Evaluation

In [12]:
def build_faster_rcnn(num_classes: int):
    # num_classes includes the background class.
    weights = FasterRCNN_ResNet50_FPN_V2_Weights.DEFAULT
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn_v2(
        weights=weights,
        min_size=IMG_SIZE,
        max_size=IMG_SIZE,
    )
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    return model


def train_faster_rcnn(seed: int):
    set_seed(seed)
    run_name = f'fasterrcnn_resnet50_fpn_v2_seed{seed}'
    run_dir = OUTPUT_ROOT / run_name
    run_dir.mkdir(parents=True, exist_ok=True)

    train_loader = make_detection_loader(train_ds, BATCH_SIZE, shuffle=True, seed=seed)
    val_loader = make_detection_loader(val_ds, BATCH_SIZE, shuffle=False)
    test_loader = make_detection_loader(test_ds, BATCH_SIZE, shuffle=False)

    model = build_faster_rcnn(NUM_CLASSES + 1).to(DEVICE)
    optimizer = torch.optim.SGD(
        [p for p in model.parameters() if p.requires_grad],
        lr=0.005,
        momentum=0.9,
        weight_decay=0.0005,
    )
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=45, gamma=0.1)

    history = []
    best_val_map = -1.0
    best_epoch = -1
    epochs_without_improvement = 0

    optimizer.zero_grad(set_to_none=True)
    for epoch in range(1, EPOCHS + 1):
        model.train()
        losses = []

        for step, (images, targets) in enumerate(train_loader, start=1):
            images = [img.to(DEVICE) for img in images]
            targets = [{k: v.to(DEVICE) for k, v in t.items()} for t in targets]

            loss_dict = model(images, targets)
            loss = sum(loss for loss in loss_dict.values())
            (loss / ACCUM_STEPS).backward()

            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)

            losses.append(float(loss.detach().cpu()))

        scheduler.step()
        val_metrics = evaluate_torchvision_detector(model, val_loader)
        mean_loss = float(np.mean(losses))
        val_map = val_metrics['mAP50-95']
        history_row = {
            'epoch': epoch,
            'train_loss': mean_loss,
            **{f'val_{k}': v for k, v in val_metrics.items()},
        }
        history.append(history_row)
        print(f'[{run_name}] epoch {epoch:03d}/{EPOCHS} train_loss={mean_loss:.4f} val_mAP50-95={val_map:.4f} val_mAP50={val_metrics["mAP50"]:.4f}')

        if val_map > best_val_map:
            best_val_map = val_map
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save({
                'model_state': model.state_dict(),
                'class_names': CLASS_NAMES,
                'img_size': IMG_SIZE,
                'seed': seed,
                'epoch': epoch,
                'best_val_mAP50-95': best_val_map,
            }, run_dir / 'best.pt')
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print(f'[{run_name}] early stopping at epoch {epoch}; best_epoch={best_epoch} best_val_mAP50-95={best_val_map:.4f}')
            break

    pd.DataFrame(history).to_csv(run_dir / 'history.csv', index=False)

    checkpoint = torch.load(run_dir / 'best.pt', map_location=DEVICE)
    model.load_state_dict(checkpoint['model_state'])
    test_metrics = evaluate_torchvision_detector(model, test_loader)
    row = {
        'model': 'Faster R-CNN ResNet50 FPN v2',
        'seed': seed,
        'run': run_name,
        'best_epoch': best_epoch,
        'best_val_mAP50-95': best_val_map,
        **test_metrics,
    }
    save_run_result(run_dir, row)
    return row


faster_rcnn_rows = []
for seed in SEEDS:
    faster_rcnn_rows.append(train_faster_rcnn(seed))

pd.DataFrame(faster_rcnn_rows)

[fasterrcnn_resnet50_fpn_v2_seed0] epoch 001/150 train_loss=0.9209 val_mAP50-95=0.1473 val_mAP50=0.4140
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 002/150 train_loss=0.5178 val_mAP50-95=0.3482 val_mAP50=0.5797
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 003/150 train_loss=0.3428 val_mAP50-95=0.4579 val_mAP50=0.6342
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 004/150 train_loss=0.2834 val_mAP50-95=0.5206 val_mAP50=0.7067
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 005/150 train_loss=0.2464 val_mAP50-95=0.5931 val_mAP50=0.7808
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 006/150 train_loss=0.2158 val_mAP50-95=0.6443 val_mAP50=0.8308
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 007/150 train_loss=0.1850 val_mAP50-95=0.6953 val_mAP50=0.8751
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 008/150 train_loss=0.1644 val_mAP50-95=0.7076 val_mAP50=0.8929
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 009/150 train_loss=0.1394 val_mAP50-95=0.7320 val_mAP50=0.9028
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 010/150 train_loss=0.1277 val_mAP50-95=0.7231 val_mAP50=0.9023
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 011/150 train_loss=0.1142 val_mAP50-95=0.7333 val_mAP50=0.9076
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 012/150 train_loss=0.1039 val_mAP50-95=0.7291 val_mAP50=0.9045
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 013/150 train_loss=0.1007 val_mAP50-95=0.7324 val_mAP50=0.9065
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 014/150 train_loss=0.0934 val_mAP50-95=0.7274 val_mAP50=0.9066
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 015/150 train_loss=0.0869 val_mAP50-95=0.7332 val_mAP50=0.9074
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 016/150 train_loss=0.0831 val_mAP50-95=0.7458 val_mAP50=0.9159
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 017/150 train_loss=0.0784 val_mAP50-95=0.7376 val_mAP50=0.9081
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 018/150 train_loss=0.0751 val_mAP50-95=0.7404 val_mAP50=0.9152
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 019/150 train_loss=0.0735 val_mAP50-95=0.7428 val_mAP50=0.9076
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 020/150 train_loss=0.0688 val_mAP50-95=0.7390 val_mAP50=0.8984
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 021/150 train_loss=0.0669 val_mAP50-95=0.7389 val_mAP50=0.9071
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 022/150 train_loss=0.0652 val_mAP50-95=0.7420 val_mAP50=0.9062
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 023/150 train_loss=0.0623 val_mAP50-95=0.7450 val_mAP50=0.9165
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 024/150 train_loss=0.0599 val_mAP50-95=0.7345 val_mAP50=0.9130
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 025/150 train_loss=0.0598 val_mAP50-95=0.7410 val_mAP50=0.9118
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 026/150 train_loss=0.0573 val_mAP50-95=0.7390 val_mAP50=0.9053
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 027/150 train_loss=0.0555 val_mAP50-95=0.7409 val_mAP50=0.9076
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 028/150 train_loss=0.0547 val_mAP50-95=0.7399 val_mAP50=0.9033
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 029/150 train_loss=0.0529 val_mAP50-95=0.7421 val_mAP50=0.8999
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 030/150 train_loss=0.0506 val_mAP50-95=0.7388 val_mAP50=0.8998
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 031/150 train_loss=0.0505 val_mAP50-95=0.7444 val_mAP50=0.9076
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 032/150 train_loss=0.0486 val_mAP50-95=0.7463 val_mAP50=0.9117
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 033/150 train_loss=0.0493 val_mAP50-95=0.7470 val_mAP50=0.9065
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 034/150 train_loss=0.0462 val_mAP50-95=0.7396 val_mAP50=0.9067
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 035/150 train_loss=0.0463 val_mAP50-95=0.7462 val_mAP50=0.9055
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 036/150 train_loss=0.0448 val_mAP50-95=0.7470 val_mAP50=0.9096
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 037/150 train_loss=0.0455 val_mAP50-95=0.7467 val_mAP50=0.9104
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 038/150 train_loss=0.0443 val_mAP50-95=0.7509 val_mAP50=0.9136
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 039/150 train_loss=0.0442 val_mAP50-95=0.7431 val_mAP50=0.9018
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 040/150 train_loss=0.0429 val_mAP50-95=0.7361 val_mAP50=0.9057
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 041/150 train_loss=0.0435 val_mAP50-95=0.7505 val_mAP50=0.9088
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 042/150 train_loss=0.0411 val_mAP50-95=0.7534 val_mAP50=0.9095
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 043/150 train_loss=0.0408 val_mAP50-95=0.7474 val_mAP50=0.9100
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 044/150 train_loss=0.0398 val_mAP50-95=0.7562 val_mAP50=0.9107
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 045/150 train_loss=0.0394 val_mAP50-95=0.7521 val_mAP50=0.9074
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 046/150 train_loss=0.0379 val_mAP50-95=0.7510 val_mAP50=0.9086
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 047/150 train_loss=0.0376 val_mAP50-95=0.7553 val_mAP50=0.9123
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 048/150 train_loss=0.0368 val_mAP50-95=0.7550 val_mAP50=0.9112
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 049/150 train_loss=0.0367 val_mAP50-95=0.7571 val_mAP50=0.9118
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 050/150 train_loss=0.0365 val_mAP50-95=0.7574 val_mAP50=0.9148
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 051/150 train_loss=0.0367 val_mAP50-95=0.7568 val_mAP50=0.9121
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 052/150 train_loss=0.0362 val_mAP50-95=0.7544 val_mAP50=0.9110
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 053/150 train_loss=0.0367 val_mAP50-95=0.7555 val_mAP50=0.9121
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 054/150 train_loss=0.0359 val_mAP50-95=0.7574 val_mAP50=0.9116
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 055/150 train_loss=0.0360 val_mAP50-95=0.7600 val_mAP50=0.9120
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 056/150 train_loss=0.0358 val_mAP50-95=0.7602 val_mAP50=0.9167
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 057/150 train_loss=0.0359 val_mAP50-95=0.7551 val_mAP50=0.9123
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 058/150 train_loss=0.0367 val_mAP50-95=0.7592 val_mAP50=0.9121
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 059/150 train_loss=0.0357 val_mAP50-95=0.7552 val_mAP50=0.9118
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 060/150 train_loss=0.0360 val_mAP50-95=0.7565 val_mAP50=0.9128
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 061/150 train_loss=0.0361 val_mAP50-95=0.7581 val_mAP50=0.9089
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 062/150 train_loss=0.0348 val_mAP50-95=0.7539 val_mAP50=0.9088
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 063/150 train_loss=0.0358 val_mAP50-95=0.7528 val_mAP50=0.9077
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 064/150 train_loss=0.0349 val_mAP50-95=0.7553 val_mAP50=0.9160
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 065/150 train_loss=0.0357 val_mAP50-95=0.7530 val_mAP50=0.9104
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 066/150 train_loss=0.0350 val_mAP50-95=0.7568 val_mAP50=0.9120
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 067/150 train_loss=0.0357 val_mAP50-95=0.7539 val_mAP50=0.9121
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 068/150 train_loss=0.0346 val_mAP50-95=0.7588 val_mAP50=0.9127
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 069/150 train_loss=0.0349 val_mAP50-95=0.7554 val_mAP50=0.9074
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 070/150 train_loss=0.0347 val_mAP50-95=0.7544 val_mAP50=0.9095
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 071/150 train_loss=0.0349 val_mAP50-95=0.7528 val_mAP50=0.9086
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 072/150 train_loss=0.0350 val_mAP50-95=0.7557 val_mAP50=0.9118
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 073/150 train_loss=0.0351 val_mAP50-95=0.7567 val_mAP50=0.9113
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 074/150 train_loss=0.0345 val_mAP50-95=0.7530 val_mAP50=0.9145
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 075/150 train_loss=0.0348 val_mAP50-95=0.7551 val_mAP50=0.9107
[fasterrcnn_resnet50_fpn_v2_seed0] epoch 076/150 train_loss=0.0348 val_mAP50-95=0.7522 val_mAP50=0.9107
[fasterrcnn_resnet50_fpn_v2_seed0] early stopping at epoch 76; best_epoch=56 best_val_mAP50-95=0.7602
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 001/150 train_loss=0.8709 val_mAP50-95=0.1690 val_mAP50=0.4247
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 002/150 train_loss=0.4921 val_mAP50-95=0.3732 val_mAP50=0.6160
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 003/150 train_loss=0.3357 val_mAP50-95=0.4853 val_mAP50=0.6891
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 004/150 train_loss=0.2783 val_mAP50-95=0.5678 val_mAP50=0.7512
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 005/150 train_loss=0.2406 val_mAP50-95=0.6362 val_mAP50=0.8201
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 006/150 train_loss=0.2030 val_mAP50-95=0.6888 val_mAP50=0.8684
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 007/150 train_loss=0.1717 val_mAP50-95=0.7102 val_mAP50=0.8914
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 008/150 train_loss=0.1502 val_mAP50-95=0.7231 val_mAP50=0.9010
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 009/150 train_loss=0.1318 val_mAP50-95=0.7299 val_mAP50=0.9074
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 010/150 train_loss=0.1191 val_mAP50-95=0.7372 val_mAP50=0.9084
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 011/150 train_loss=0.1092 val_mAP50-95=0.7378 val_mAP50=0.9085
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 012/150 train_loss=0.1023 val_mAP50-95=0.7310 val_mAP50=0.9062
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 013/150 train_loss=0.0955 val_mAP50-95=0.7377 val_mAP50=0.9115
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 014/150 train_loss=0.0918 val_mAP50-95=0.7388 val_mAP50=0.9109
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 015/150 train_loss=0.0849 val_mAP50-95=0.7445 val_mAP50=0.9112
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 016/150 train_loss=0.0791 val_mAP50-95=0.7460 val_mAP50=0.9125
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 017/150 train_loss=0.0769 val_mAP50-95=0.7513 val_mAP50=0.9109
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 018/150 train_loss=0.0737 val_mAP50-95=0.7478 val_mAP50=0.9071
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 019/150 train_loss=0.0707 val_mAP50-95=0.7500 val_mAP50=0.9070
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 020/150 train_loss=0.0698 val_mAP50-95=0.7373 val_mAP50=0.9091
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 021/150 train_loss=0.0653 val_mAP50-95=0.7506 val_mAP50=0.9137
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 022/150 train_loss=0.0640 val_mAP50-95=0.7460 val_mAP50=0.9119
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 023/150 train_loss=0.0635 val_mAP50-95=0.7340 val_mAP50=0.9000
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 024/150 train_loss=0.0618 val_mAP50-95=0.7545 val_mAP50=0.9170
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 025/150 train_loss=0.0583 val_mAP50-95=0.7485 val_mAP50=0.9123
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 026/150 train_loss=0.0576 val_mAP50-95=0.7446 val_mAP50=0.9039
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 027/150 train_loss=0.0540 val_mAP50-95=0.7489 val_mAP50=0.9104
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 028/150 train_loss=0.0541 val_mAP50-95=0.7427 val_mAP50=0.9060
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 029/150 train_loss=0.0549 val_mAP50-95=0.7536 val_mAP50=0.9166
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 030/150 train_loss=0.0517 val_mAP50-95=0.7549 val_mAP50=0.9107
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 031/150 train_loss=0.0491 val_mAP50-95=0.7569 val_mAP50=0.9140
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 032/150 train_loss=0.0484 val_mAP50-95=0.7547 val_mAP50=0.9111
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 033/150 train_loss=0.0472 val_mAP50-95=0.7465 val_mAP50=0.8990
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 034/150 train_loss=0.0478 val_mAP50-95=0.7507 val_mAP50=0.9106
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 035/150 train_loss=0.0485 val_mAP50-95=0.7534 val_mAP50=0.9137
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 036/150 train_loss=0.0462 val_mAP50-95=0.7531 val_mAP50=0.9065
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 037/150 train_loss=0.0456 val_mAP50-95=0.7522 val_mAP50=0.9073
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 038/150 train_loss=0.0444 val_mAP50-95=0.7484 val_mAP50=0.9088
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 039/150 train_loss=0.0432 val_mAP50-95=0.7484 val_mAP50=0.8948
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 040/150 train_loss=0.0439 val_mAP50-95=0.7547 val_mAP50=0.9101
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 041/150 train_loss=0.0417 val_mAP50-95=0.7550 val_mAP50=0.9153
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 042/150 train_loss=0.0416 val_mAP50-95=0.7504 val_mAP50=0.9077
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 043/150 train_loss=0.0417 val_mAP50-95=0.7547 val_mAP50=0.9039
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 044/150 train_loss=0.0403 val_mAP50-95=0.7555 val_mAP50=0.9064
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 045/150 train_loss=0.0387 val_mAP50-95=0.7605 val_mAP50=0.9136
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 046/150 train_loss=0.0384 val_mAP50-95=0.7634 val_mAP50=0.9136
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 047/150 train_loss=0.0368 val_mAP50-95=0.7606 val_mAP50=0.9109
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 048/150 train_loss=0.0374 val_mAP50-95=0.7622 val_mAP50=0.9125
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 049/150 train_loss=0.0367 val_mAP50-95=0.7567 val_mAP50=0.9129
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 050/150 train_loss=0.0377 val_mAP50-95=0.7645 val_mAP50=0.9131
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 051/150 train_loss=0.0362 val_mAP50-95=0.7667 val_mAP50=0.9215
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 052/150 train_loss=0.0363 val_mAP50-95=0.7607 val_mAP50=0.9172
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 053/150 train_loss=0.0358 val_mAP50-95=0.7545 val_mAP50=0.9066
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 054/150 train_loss=0.0362 val_mAP50-95=0.7638 val_mAP50=0.9145
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 055/150 train_loss=0.0360 val_mAP50-95=0.7587 val_mAP50=0.9143
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 056/150 train_loss=0.0358 val_mAP50-95=0.7636 val_mAP50=0.9189
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 057/150 train_loss=0.0357 val_mAP50-95=0.7645 val_mAP50=0.9177
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 058/150 train_loss=0.0357 val_mAP50-95=0.7650 val_mAP50=0.9147
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 059/150 train_loss=0.0358 val_mAP50-95=0.7620 val_mAP50=0.9113
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 060/150 train_loss=0.0350 val_mAP50-95=0.7595 val_mAP50=0.9145
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 061/150 train_loss=0.0356 val_mAP50-95=0.7632 val_mAP50=0.9147
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 062/150 train_loss=0.0347 val_mAP50-95=0.7603 val_mAP50=0.9141
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 063/150 train_loss=0.0356 val_mAP50-95=0.7600 val_mAP50=0.9139
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 064/150 train_loss=0.0358 val_mAP50-95=0.7621 val_mAP50=0.9138
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 065/150 train_loss=0.0351 val_mAP50-95=0.7641 val_mAP50=0.9158
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 066/150 train_loss=0.0351 val_mAP50-95=0.7593 val_mAP50=0.9114
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 067/150 train_loss=0.0353 val_mAP50-95=0.7650 val_mAP50=0.9139
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 068/150 train_loss=0.0353 val_mAP50-95=0.7606 val_mAP50=0.9144
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 069/150 train_loss=0.0355 val_mAP50-95=0.7616 val_mAP50=0.9148
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 070/150 train_loss=0.0347 val_mAP50-95=0.7537 val_mAP50=0.9062
[fasterrcnn_resnet50_fpn_v2_seed1] epoch 071/150 train_loss=0.0345 val_mAP50-95=0.7628 val_mAP50=0.9138
[fasterrcnn_resnet50_fpn_v2_seed1] early stopping at epoch 71; best_epoch=51 best_val_mAP50-95=0.7667
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 001/150 train_loss=0.8809 val_mAP50-95=0.1549 val_mAP50=0.4205
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 002/150 train_loss=0.4791 val_mAP50-95=0.4056 val_mAP50=0.6163
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 003/150 train_loss=0.3299 val_mAP50-95=0.4863 val_mAP50=0.6682
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 004/150 train_loss=0.2743 val_mAP50-95=0.5831 val_mAP50=0.7721
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 005/150 train_loss=0.2330 val_mAP50-95=0.6534 val_mAP50=0.8360
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 006/150 train_loss=0.1929 val_mAP50-95=0.7086 val_mAP50=0.8810
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 007/150 train_loss=0.1650 val_mAP50-95=0.7223 val_mAP50=0.8980
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 008/150 train_loss=0.1450 val_mAP50-95=0.7311 val_mAP50=0.9073
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 009/150 train_loss=0.1303 val_mAP50-95=0.7196 val_mAP50=0.9085
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 010/150 train_loss=0.1182 val_mAP50-95=0.7328 val_mAP50=0.9048
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 011/150 train_loss=0.1086 val_mAP50-95=0.7294 val_mAP50=0.9007
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 012/150 train_loss=0.1003 val_mAP50-95=0.7328 val_mAP50=0.9083
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 013/150 train_loss=0.0962 val_mAP50-95=0.7339 val_mAP50=0.9067
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 014/150 train_loss=0.0903 val_mAP50-95=0.7436 val_mAP50=0.9110
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 015/150 train_loss=0.0850 val_mAP50-95=0.7406 val_mAP50=0.9098
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 016/150 train_loss=0.0820 val_mAP50-95=0.7447 val_mAP50=0.9088
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 017/150 train_loss=0.0775 val_mAP50-95=0.7478 val_mAP50=0.9061
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 018/150 train_loss=0.0746 val_mAP50-95=0.7382 val_mAP50=0.9078
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 019/150 train_loss=0.0724 val_mAP50-95=0.7482 val_mAP50=0.9073
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 020/150 train_loss=0.0679 val_mAP50-95=0.7448 val_mAP50=0.9045
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 021/150 train_loss=0.0650 val_mAP50-95=0.7474 val_mAP50=0.9088
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 022/150 train_loss=0.0640 val_mAP50-95=0.7527 val_mAP50=0.9132
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 023/150 train_loss=0.0626 val_mAP50-95=0.7477 val_mAP50=0.9069
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 024/150 train_loss=0.0613 val_mAP50-95=0.7578 val_mAP50=0.9151
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 025/150 train_loss=0.0575 val_mAP50-95=0.7472 val_mAP50=0.9044
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 026/150 train_loss=0.0577 val_mAP50-95=0.7476 val_mAP50=0.9136
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 027/150 train_loss=0.0573 val_mAP50-95=0.7522 val_mAP50=0.9137
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 028/150 train_loss=0.0555 val_mAP50-95=0.7603 val_mAP50=0.9152
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 029/150 train_loss=0.0523 val_mAP50-95=0.7580 val_mAP50=0.9132
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 030/150 train_loss=0.0510 val_mAP50-95=0.7586 val_mAP50=0.9154
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 031/150 train_loss=0.0499 val_mAP50-95=0.7544 val_mAP50=0.9116
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 032/150 train_loss=0.0498 val_mAP50-95=0.7504 val_mAP50=0.9105
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 033/150 train_loss=0.0478 val_mAP50-95=0.7595 val_mAP50=0.9139
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 034/150 train_loss=0.0470 val_mAP50-95=0.7608 val_mAP50=0.9113
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 035/150 train_loss=0.0462 val_mAP50-95=0.7557 val_mAP50=0.9079
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 036/150 train_loss=0.0439 val_mAP50-95=0.7582 val_mAP50=0.9066
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 037/150 train_loss=0.0443 val_mAP50-95=0.7567 val_mAP50=0.9133
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 038/150 train_loss=0.0434 val_mAP50-95=0.7557 val_mAP50=0.9092
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 039/150 train_loss=0.0434 val_mAP50-95=0.7633 val_mAP50=0.9167
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 040/150 train_loss=0.0435 val_mAP50-95=0.7491 val_mAP50=0.9069
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 041/150 train_loss=0.0435 val_mAP50-95=0.7547 val_mAP50=0.9068
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 042/150 train_loss=0.0422 val_mAP50-95=0.7458 val_mAP50=0.9011
[fasterrcnn_resnet50_fpn_v2_seed2] epoch 043/150 train_loss=0.0418 val_mAP50-95=0.7607 val_mAP50=0.9106

,model,seed,run,best_epoch,best_val_mAP50-95,precision,recall,mAP50,mAP50-95,inference_ms
0,Faster R-CNN ResNet50 FPN v2,0,fasterrcnn_resnet50_fpn_v2_seed0,56,0.760215,0.564639,0.928125,0.874963,0.707457,16.991587
1,Faster R-CNN ResNet50 FPN v2,1,fasterrcnn_resnet50_fpn_v2_seed1,51,0.766708,0.610063,0.909375,0.860846,0.691223,13.431556
2,Faster R-CNN ResNet50 FPN v2,2,fasterrcnn_resnet50_fpn_v2_seed2,83,0.769670,0.601240,0.909375,0.858685,0.690967,13.811558

## EfficientDet Training And Evaluation

In [15]:
from effdet import create_model


def build_efficientdet_train(num_classes: int):
    return create_model(
        'tf_efficientdet_d0',
        bench_task='train',
        bench_labeler=True,
        num_classes=num_classes,
        pretrained=True,
        image_size=(IMG_SIZE, IMG_SIZE),
    )


def build_efficientdet_predict(num_classes: int):
    return create_model(
        'tf_efficientdet_d0',
        bench_task='predict',
        num_classes=num_classes,
        pretrained=False,
        image_size=(IMG_SIZE, IMG_SIZE),
    )


def parse_effdet_detections(detections: torch.Tensor):
    # effdet predict bench returns detections shaped [B, N, 6]: x1, y1, x2, y2, score, class.
    preds = []
    detections = detections.detach().cpu()
    for det in detections:
        if det.numel() == 0:
            preds.append({
                'boxes': torch.zeros((0, 4), dtype=torch.float32),
                'scores': torch.zeros((0,), dtype=torch.float32),
                'labels': torch.zeros((0,), dtype=torch.int64),
            })
            continue
        scores = det[:, 4]
        keep = scores >= SCORE_THRESHOLD
        labels = det[:, 5].to(torch.int64)
        labels = torch.clamp(labels, min=1, max=NUM_CLASSES)
        preds.append({
            'boxes': det[:, :4][keep].to(torch.float32),
            'scores': scores[keep].to(torch.float32),
            'labels': labels[keep],
        })
    return preds


@torch.no_grad()
def evaluate_efficientdet_from_checkpoint(checkpoint_path: Path, data_loader, device=DEVICE):
    model = build_efficientdet_predict(NUM_CLASSES).to(device)
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint['model_state'], strict=False)
    model.eval()

    metric = MeanAveragePrecision(box_format='xyxy', iou_type='bbox')
    pr_counts = new_pr_counts()
    total_infer_ms = []

    for images, targets in data_loader:
        images = torch.stack([img for img in images], dim=0).to(device)
        img_info = {
            'img_scale': torch.ones((images.shape[0],), dtype=torch.float32, device=device),
            'img_size': torch.full((images.shape[0], 2), IMG_SIZE, dtype=torch.float32, device=device),
        }
        metric_targets = [
            {'boxes': t['boxes'].cpu(), 'labels': t['labels'].cpu()}
            for t in targets
        ]

        if device == 'cuda':
            torch.cuda.synchronize()
        t0 = time.perf_counter()
        detections = model(images, img_info)
        if device == 'cuda':
            torch.cuda.synchronize()
        total_infer_ms.append((time.perf_counter() - t0) * 1000.0 / max(1, images.shape[0]))

        if isinstance(detections, (tuple, list)):
            detections = detections[0]
        preds = parse_effdet_detections(detections)
        metric.update(preds, metric_targets)
        update_pr_counts(preds, metric_targets, pr_counts, iou_threshold=0.5)

    result = metric.compute()
    row = metric_to_row(result, pr_counts)
    row['inference_ms'] = float(np.mean(total_infer_ms)) if total_infer_ms else np.nan
    return row


def train_efficientdet(seed: int):
    set_seed(seed)
    run_name = f'efficientdet_d0_seed{seed}'
    run_dir = OUTPUT_ROOT / run_name
    run_dir.mkdir(parents=True, exist_ok=True)

    train_loader = make_effdet_loader(eff_train_ds, BATCH_SIZE, shuffle=True, seed=seed)
    val_loader = make_detection_loader(val_ds, BATCH_SIZE, shuffle=False)
    test_loader = make_detection_loader(test_ds, BATCH_SIZE, shuffle=False)

    model = build_efficientdet_train(NUM_CLASSES).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

    history = []
    best_val_map = -1.0
    best_epoch = -1
    epochs_without_improvement = 0
    tmp_checkpoint = run_dir / '_epoch_tmp.pt'

    optimizer.zero_grad(set_to_none=True)
    for epoch in range(1, EPOCHS + 1):
        model.train()
        losses = []

        for step, (images, targets) in enumerate(train_loader, start=1):
            images = images.to(DEVICE)
            targets = {k: v.to(DEVICE) for k, v in targets.items()}

            loss_dict = model(images, targets)
            loss = loss_dict['loss'] if isinstance(loss_dict, dict) else loss_dict
            (loss / ACCUM_STEPS).backward()

            if step % ACCUM_STEPS == 0 or step == len(train_loader):
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)

            losses.append(float(loss.detach().cpu()))

        scheduler.step()
        torch.save({
            'model_state': model.state_dict(),
            'class_names': CLASS_NAMES,
            'img_size': IMG_SIZE,
            'seed': seed,
            'epoch': epoch,
        }, tmp_checkpoint)
        val_metrics = evaluate_efficientdet_from_checkpoint(tmp_checkpoint, val_loader)
        mean_loss = float(np.mean(losses))
        val_map = val_metrics['mAP50-95']
        history_row = {
            'epoch': epoch,
            'train_loss': mean_loss,
            **{f'val_{k}': v for k, v in val_metrics.items()},
        }
        history.append(history_row)
        print(f'[{run_name}] epoch {epoch:03d}/{EPOCHS} train_loss={mean_loss:.4f} val_mAP50-95={val_map:.4f} val_mAP50={val_metrics["mAP50"]:.4f}')

        if val_map > best_val_map:
            best_val_map = val_map
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save({
                'model_state': model.state_dict(),
                'class_names': CLASS_NAMES,
                'img_size': IMG_SIZE,
                'seed': seed,
                'epoch': epoch,
                'best_val_mAP50-95': best_val_map,
            }, run_dir / 'best.pt')
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print(f'[{run_name}] early stopping at epoch {epoch}; best_epoch={best_epoch} best_val_mAP50-95={best_val_map:.4f}')
            break

    pd.DataFrame(history).to_csv(run_dir / 'history.csv', index=False)
    tmp_checkpoint.unlink(missing_ok=True)

    test_metrics = evaluate_efficientdet_from_checkpoint(run_dir / 'best.pt', test_loader)
    row = {
        'model': 'EfficientDet-D0',
        'seed': seed,
        'run': run_name,
        'best_epoch': best_epoch,
        'best_val_mAP50-95': best_val_map,
        **test_metrics,
    }
    save_run_result(run_dir, row)
    return row


efficientdet_rows = []
for seed in SEEDS:
    efficientdet_rows.append(train_efficientdet(seed))

pd.DataFrame(efficientdet_rows)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B / 21.4MB

model.safetensors: downloading bytes:           |  0.00B

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 001/150 train_loss=1.3989 val_mAP50-95=0.0652 val_mAP50=0.1492

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 002/150 train_loss=1.1487 val_mAP50-95=0.1817 val_mAP50=0.3280

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 003/150 train_loss=1.0019 val_mAP50-95=0.2503 val_mAP50=0.4176

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 004/150 train_loss=0.8991 val_mAP50-95=0.2963 val_mAP50=0.4760

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 005/150 train_loss=0.8070 val_mAP50-95=0.3331 val_mAP50=0.5125

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 006/150 train_loss=0.7275 val_mAP50-95=0.3902 val_mAP50=0.5818

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 007/150 train_loss=0.6501 val_mAP50-95=0.4756 val_mAP50=0.6872

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 008/150 train_loss=0.5914 val_mAP50-95=0.5253 val_mAP50=0.7509

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 009/150 train_loss=0.5279 val_mAP50-95=0.5669 val_mAP50=0.7904

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 010/150 train_loss=0.4841 val_mAP50-95=0.5834 val_mAP50=0.8166

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 011/150 train_loss=0.4450 val_mAP50-95=0.6119 val_mAP50=0.8441

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 012/150 train_loss=0.4108 val_mAP50-95=0.6233 val_mAP50=0.8506

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 013/150 train_loss=0.3883 val_mAP50-95=0.6347 val_mAP50=0.8590

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 014/150 train_loss=0.3679 val_mAP50-95=0.6501 val_mAP50=0.8750

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 015/150 train_loss=0.3438 val_mAP50-95=0.6560 val_mAP50=0.8850

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 016/150 train_loss=0.3309 val_mAP50-95=0.6632 val_mAP50=0.8861

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 017/150 train_loss=0.3154 val_mAP50-95=0.6695 val_mAP50=0.8896

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 018/150 train_loss=0.3042 val_mAP50-95=0.6781 val_mAP50=0.9006

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 019/150 train_loss=0.2927 val_mAP50-95=0.6724 val_mAP50=0.8974

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 020/150 train_loss=0.2774 val_mAP50-95=0.6828 val_mAP50=0.9013

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 021/150 train_loss=0.2735 val_mAP50-95=0.6844 val_mAP50=0.9029

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 022/150 train_loss=0.2650 val_mAP50-95=0.6907 val_mAP50=0.9090

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 023/150 train_loss=0.2517 val_mAP50-95=0.6963 val_mAP50=0.9099

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 024/150 train_loss=0.2462 val_mAP50-95=0.6973 val_mAP50=0.9074

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 025/150 train_loss=0.2401 val_mAP50-95=0.6982 val_mAP50=0.9124

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 026/150 train_loss=0.2333 val_mAP50-95=0.6948 val_mAP50=0.9126

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 027/150 train_loss=0.2271 val_mAP50-95=0.7048 val_mAP50=0.9140

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 028/150 train_loss=0.2206 val_mAP50-95=0.6997 val_mAP50=0.9155

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 029/150 train_loss=0.2144 val_mAP50-95=0.7009 val_mAP50=0.9169

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 030/150 train_loss=0.2149 val_mAP50-95=0.7022 val_mAP50=0.9151

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 031/150 train_loss=0.2084 val_mAP50-95=0.6978 val_mAP50=0.9177

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 032/150 train_loss=0.2026 val_mAP50-95=0.7026 val_mAP50=0.9159

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 033/150 train_loss=0.1989 val_mAP50-95=0.7021 val_mAP50=0.9174

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 034/150 train_loss=0.1918 val_mAP50-95=0.7057 val_mAP50=0.9168

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 035/150 train_loss=0.1885 val_mAP50-95=0.7102 val_mAP50=0.9201

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 036/150 train_loss=0.1847 val_mAP50-95=0.7078 val_mAP50=0.9177

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 037/150 train_loss=0.1837 val_mAP50-95=0.7065 val_mAP50=0.9152

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 038/150 train_loss=0.1779 val_mAP50-95=0.7077 val_mAP50=0.9176

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 039/150 train_loss=0.1789 val_mAP50-95=0.7022 val_mAP50=0.9155

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 040/150 train_loss=0.1722 val_mAP50-95=0.7088 val_mAP50=0.9177

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 041/150 train_loss=0.1699 val_mAP50-95=0.7053 val_mAP50=0.9183

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 042/150 train_loss=0.1690 val_mAP50-95=0.7107 val_mAP50=0.9202

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 043/150 train_loss=0.1652 val_mAP50-95=0.7094 val_mAP50=0.9196

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 044/150 train_loss=0.1607 val_mAP50-95=0.7083 val_mAP50=0.9164

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 045/150 train_loss=0.1586 val_mAP50-95=0.7109 val_mAP50=0.9199

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 046/150 train_loss=0.1550 val_mAP50-95=0.7075 val_mAP50=0.9178

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 047/150 train_loss=0.1549 val_mAP50-95=0.7139 val_mAP50=0.9197

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 048/150 train_loss=0.1510 val_mAP50-95=0.7179 val_mAP50=0.9225

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 049/150 train_loss=0.1493 val_mAP50-95=0.7196 val_mAP50=0.9221

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 050/150 train_loss=0.1469 val_mAP50-95=0.7178 val_mAP50=0.9210

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 051/150 train_loss=0.1469 val_mAP50-95=0.7130 val_mAP50=0.9147

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 052/150 train_loss=0.1440 val_mAP50-95=0.7121 val_mAP50=0.9153

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 053/150 train_loss=0.1434 val_mAP50-95=0.7156 val_mAP50=0.9192

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 054/150 train_loss=0.1384 val_mAP50-95=0.7198 val_mAP50=0.9232

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 055/150 train_loss=0.1371 val_mAP50-95=0.7205 val_mAP50=0.9209

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 056/150 train_loss=0.1361 val_mAP50-95=0.7162 val_mAP50=0.9226

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 057/150 train_loss=0.1343 val_mAP50-95=0.7184 val_mAP50=0.9203

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 058/150 train_loss=0.1329 val_mAP50-95=0.7197 val_mAP50=0.9210

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 059/150 train_loss=0.1307 val_mAP50-95=0.7156 val_mAP50=0.9205

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 060/150 train_loss=0.1287 val_mAP50-95=0.7234 val_mAP50=0.9227

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 061/150 train_loss=0.1298 val_mAP50-95=0.7197 val_mAP50=0.9209

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 062/150 train_loss=0.1275 val_mAP50-95=0.7207 val_mAP50=0.9215

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 063/150 train_loss=0.1258 val_mAP50-95=0.7214 val_mAP50=0.9230

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 064/150 train_loss=0.1235 val_mAP50-95=0.7255 val_mAP50=0.9226

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 065/150 train_loss=0.1233 val_mAP50-95=0.7208 val_mAP50=0.9217

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 066/150 train_loss=0.1241 val_mAP50-95=0.7214 val_mAP50=0.9230

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 067/150 train_loss=0.1192 val_mAP50-95=0.7206 val_mAP50=0.9236

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 068/150 train_loss=0.1175 val_mAP50-95=0.7242 val_mAP50=0.9221

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 069/150 train_loss=0.1163 val_mAP50-95=0.7245 val_mAP50=0.9231

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 070/150 train_loss=0.1163 val_mAP50-95=0.7246 val_mAP50=0.9242

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 071/150 train_loss=0.1144 val_mAP50-95=0.7281 val_mAP50=0.9265

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 072/150 train_loss=0.1144 val_mAP50-95=0.7175 val_mAP50=0.9200

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 073/150 train_loss=0.1121 val_mAP50-95=0.7210 val_mAP50=0.9200

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 074/150 train_loss=0.1100 val_mAP50-95=0.7258 val_mAP50=0.9201

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 075/150 train_loss=0.1094 val_mAP50-95=0.7225 val_mAP50=0.9208

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 076/150 train_loss=0.1088 val_mAP50-95=0.7221 val_mAP50=0.9202

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 077/150 train_loss=0.1088 val_mAP50-95=0.7259 val_mAP50=0.9228

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 078/150 train_loss=0.1085 val_mAP50-95=0.7264 val_mAP50=0.9222

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 079/150 train_loss=0.1080 val_mAP50-95=0.7211 val_mAP50=0.9225

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 080/150 train_loss=0.1059 val_mAP50-95=0.7213 val_mAP50=0.9194

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 081/150 train_loss=0.1066 val_mAP50-95=0.7265 val_mAP50=0.9232

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 082/150 train_loss=0.1027 val_mAP50-95=0.7233 val_mAP50=0.9216

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 083/150 train_loss=0.1034 val_mAP50-95=0.7250 val_mAP50=0.9229

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 084/150 train_loss=0.1041 val_mAP50-95=0.7231 val_mAP50=0.9215

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 085/150 train_loss=0.1041 val_mAP50-95=0.7255 val_mAP50=0.9226

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 086/150 train_loss=0.1012 val_mAP50-95=0.7276 val_mAP50=0.9225

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 087/150 train_loss=0.1004 val_mAP50-95=0.7221 val_mAP50=0.9214

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 088/150 train_loss=0.1005 val_mAP50-95=0.7298 val_mAP50=0.9236

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 089/150 train_loss=0.0982 val_mAP50-95=0.7283 val_mAP50=0.9233

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 090/150 train_loss=0.1012 val_mAP50-95=0.7290 val_mAP50=0.9227

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 091/150 train_loss=0.0971 val_mAP50-95=0.7257 val_mAP50=0.9237

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 092/150 train_loss=0.0989 val_mAP50-95=0.7287 val_mAP50=0.9252

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 093/150 train_loss=0.0974 val_mAP50-95=0.7281 val_mAP50=0.9246

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 094/150 train_loss=0.0958 val_mAP50-95=0.7260 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 095/150 train_loss=0.0947 val_mAP50-95=0.7299 val_mAP50=0.9247

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 096/150 train_loss=0.0951 val_mAP50-95=0.7276 val_mAP50=0.9239

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 097/150 train_loss=0.0955 val_mAP50-95=0.7296 val_mAP50=0.9241

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 098/150 train_loss=0.0941 val_mAP50-95=0.7314 val_mAP50=0.9247

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 099/150 train_loss=0.0925 val_mAP50-95=0.7288 val_mAP50=0.9238

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 100/150 train_loss=0.0937 val_mAP50-95=0.7316 val_mAP50=0.9276

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 101/150 train_loss=0.0936 val_mAP50-95=0.7284 val_mAP50=0.9252

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 102/150 train_loss=0.0931 val_mAP50-95=0.7273 val_mAP50=0.9242

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 103/150 train_loss=0.0916 val_mAP50-95=0.7281 val_mAP50=0.9236

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 104/150 train_loss=0.0918 val_mAP50-95=0.7265 val_mAP50=0.9237

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 105/150 train_loss=0.0899 val_mAP50-95=0.7295 val_mAP50=0.9246

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 106/150 train_loss=0.0901 val_mAP50-95=0.7288 val_mAP50=0.9221

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 107/150 train_loss=0.0904 val_mAP50-95=0.7303 val_mAP50=0.9252

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 108/150 train_loss=0.0886 val_mAP50-95=0.7297 val_mAP50=0.9251

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 109/150 train_loss=0.0885 val_mAP50-95=0.7301 val_mAP50=0.9253

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 110/150 train_loss=0.0897 val_mAP50-95=0.7244 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 111/150 train_loss=0.0880 val_mAP50-95=0.7297 val_mAP50=0.9244

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 112/150 train_loss=0.0879 val_mAP50-95=0.7302 val_mAP50=0.9259

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 113/150 train_loss=0.0890 val_mAP50-95=0.7311 val_mAP50=0.9244

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 114/150 train_loss=0.0870 val_mAP50-95=0.7311 val_mAP50=0.9241

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 115/150 train_loss=0.0867 val_mAP50-95=0.7280 val_mAP50=0.9255

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 116/150 train_loss=0.0870 val_mAP50-95=0.7257 val_mAP50=0.9236

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 117/150 train_loss=0.0868 val_mAP50-95=0.7282 val_mAP50=0.9253

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 118/150 train_loss=0.0872 val_mAP50-95=0.7256 val_mAP50=0.9239

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 119/150 train_loss=0.0864 val_mAP50-95=0.7307 val_mAP50=0.9247

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed0] epoch 120/150 train_loss=0.0865 val_mAP50-95=0.7288 val_mAP50=0.9235
[efficientdet_d0_seed0] early stopping at epoch 120; best_epoch=100 best_val_mAP50-95=0.7316

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 001/150 train_loss=1.3951 val_mAP50-95=0.0806 val_mAP50=0.1741

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 002/150 train_loss=1.1447 val_mAP50-95=0.1904 val_mAP50=0.3556

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 003/150 train_loss=0.9935 val_mAP50-95=0.2573 val_mAP50=0.4259

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 004/150 train_loss=0.8771 val_mAP50-95=0.3129 val_mAP50=0.4937

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 005/150 train_loss=0.7691 val_mAP50-95=0.3849 val_mAP50=0.5850

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 006/150 train_loss=0.6821 val_mAP50-95=0.4649 val_mAP50=0.6708

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 007/150 train_loss=0.6102 val_mAP50-95=0.5002 val_mAP50=0.7240

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 008/150 train_loss=0.5490 val_mAP50-95=0.5337 val_mAP50=0.7606

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 009/150 train_loss=0.5046 val_mAP50-95=0.5674 val_mAP50=0.8063

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 010/150 train_loss=0.4635 val_mAP50-95=0.5957 val_mAP50=0.8375

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 011/150 train_loss=0.4299 val_mAP50-95=0.6098 val_mAP50=0.8497

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 012/150 train_loss=0.4054 val_mAP50-95=0.6238 val_mAP50=0.8691

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 013/150 train_loss=0.3775 val_mAP50-95=0.6419 val_mAP50=0.8782

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 014/150 train_loss=0.3585 val_mAP50-95=0.6503 val_mAP50=0.8895

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 015/150 train_loss=0.3415 val_mAP50-95=0.6561 val_mAP50=0.8953

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 016/150 train_loss=0.3282 val_mAP50-95=0.6583 val_mAP50=0.8954

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 017/150 train_loss=0.3133 val_mAP50-95=0.6605 val_mAP50=0.8949

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 018/150 train_loss=0.2955 val_mAP50-95=0.6713 val_mAP50=0.9002

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 019/150 train_loss=0.2877 val_mAP50-95=0.6809 val_mAP50=0.9108

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 020/150 train_loss=0.2785 val_mAP50-95=0.6789 val_mAP50=0.9022

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 021/150 train_loss=0.2655 val_mAP50-95=0.6829 val_mAP50=0.9073

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 022/150 train_loss=0.2589 val_mAP50-95=0.6859 val_mAP50=0.9092

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 023/150 train_loss=0.2514 val_mAP50-95=0.6897 val_mAP50=0.9087

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 024/150 train_loss=0.2433 val_mAP50-95=0.6936 val_mAP50=0.9110

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 025/150 train_loss=0.2323 val_mAP50-95=0.6954 val_mAP50=0.9143

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 026/150 train_loss=0.2263 val_mAP50-95=0.6995 val_mAP50=0.9084

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 027/150 train_loss=0.2234 val_mAP50-95=0.6966 val_mAP50=0.9116

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 028/150 train_loss=0.2189 val_mAP50-95=0.6957 val_mAP50=0.9098

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 029/150 train_loss=0.2096 val_mAP50-95=0.7028 val_mAP50=0.9158

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 030/150 train_loss=0.2062 val_mAP50-95=0.7091 val_mAP50=0.9159

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 031/150 train_loss=0.2023 val_mAP50-95=0.7041 val_mAP50=0.9143

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 032/150 train_loss=0.1966 val_mAP50-95=0.6991 val_mAP50=0.9137

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 033/150 train_loss=0.1924 val_mAP50-95=0.7067 val_mAP50=0.9166

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 034/150 train_loss=0.1883 val_mAP50-95=0.7097 val_mAP50=0.9199

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 035/150 train_loss=0.1888 val_mAP50-95=0.7029 val_mAP50=0.9163

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 036/150 train_loss=0.1823 val_mAP50-95=0.7096 val_mAP50=0.9197

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 037/150 train_loss=0.1812 val_mAP50-95=0.7103 val_mAP50=0.9192

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 038/150 train_loss=0.1758 val_mAP50-95=0.7095 val_mAP50=0.9179

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 039/150 train_loss=0.1722 val_mAP50-95=0.7050 val_mAP50=0.9159

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 040/150 train_loss=0.1684 val_mAP50-95=0.7113 val_mAP50=0.9218

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 041/150 train_loss=0.1682 val_mAP50-95=0.7131 val_mAP50=0.9212

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 042/150 train_loss=0.1626 val_mAP50-95=0.7106 val_mAP50=0.9169

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 043/150 train_loss=0.1588 val_mAP50-95=0.7122 val_mAP50=0.9201

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 044/150 train_loss=0.1597 val_mAP50-95=0.7101 val_mAP50=0.9177

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 045/150 train_loss=0.1562 val_mAP50-95=0.7117 val_mAP50=0.9205

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 046/150 train_loss=0.1545 val_mAP50-95=0.7119 val_mAP50=0.9226

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 047/150 train_loss=0.1512 val_mAP50-95=0.7089 val_mAP50=0.9188

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 048/150 train_loss=0.1494 val_mAP50-95=0.7104 val_mAP50=0.9203

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 049/150 train_loss=0.1456 val_mAP50-95=0.7160 val_mAP50=0.9224

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 050/150 train_loss=0.1462 val_mAP50-95=0.7171 val_mAP50=0.9242

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 051/150 train_loss=0.1437 val_mAP50-95=0.7174 val_mAP50=0.9252

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 052/150 train_loss=0.1404 val_mAP50-95=0.7143 val_mAP50=0.9202

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 053/150 train_loss=0.1373 val_mAP50-95=0.7134 val_mAP50=0.9217

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 054/150 train_loss=0.1353 val_mAP50-95=0.7162 val_mAP50=0.9232

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 055/150 train_loss=0.1346 val_mAP50-95=0.7179 val_mAP50=0.9259

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 056/150 train_loss=0.1335 val_mAP50-95=0.7149 val_mAP50=0.9251

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 057/150 train_loss=0.1311 val_mAP50-95=0.7165 val_mAP50=0.9256

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 058/150 train_loss=0.1311 val_mAP50-95=0.7187 val_mAP50=0.9222

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 059/150 train_loss=0.1283 val_mAP50-95=0.7132 val_mAP50=0.9213

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 060/150 train_loss=0.1275 val_mAP50-95=0.7163 val_mAP50=0.9243

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 061/150 train_loss=0.1253 val_mAP50-95=0.7170 val_mAP50=0.9216

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 062/150 train_loss=0.1275 val_mAP50-95=0.7155 val_mAP50=0.9190

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 063/150 train_loss=0.1221 val_mAP50-95=0.7191 val_mAP50=0.9215

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 064/150 train_loss=0.1223 val_mAP50-95=0.7203 val_mAP50=0.9228

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 065/150 train_loss=0.1211 val_mAP50-95=0.7157 val_mAP50=0.9179

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 066/150 train_loss=0.1199 val_mAP50-95=0.7175 val_mAP50=0.9199

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 067/150 train_loss=0.1176 val_mAP50-95=0.7186 val_mAP50=0.9224

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 068/150 train_loss=0.1189 val_mAP50-95=0.7186 val_mAP50=0.9216

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 069/150 train_loss=0.1152 val_mAP50-95=0.7207 val_mAP50=0.9244

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 070/150 train_loss=0.1151 val_mAP50-95=0.7200 val_mAP50=0.9212

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 071/150 train_loss=0.1132 val_mAP50-95=0.7201 val_mAP50=0.9243

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 072/150 train_loss=0.1139 val_mAP50-95=0.7206 val_mAP50=0.9239

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 073/150 train_loss=0.1119 val_mAP50-95=0.7192 val_mAP50=0.9221

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 074/150 train_loss=0.1103 val_mAP50-95=0.7159 val_mAP50=0.9233

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 075/150 train_loss=0.1093 val_mAP50-95=0.7169 val_mAP50=0.9196

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 076/150 train_loss=0.1090 val_mAP50-95=0.7180 val_mAP50=0.9229

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 077/150 train_loss=0.1096 val_mAP50-95=0.7178 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 078/150 train_loss=0.1068 val_mAP50-95=0.7196 val_mAP50=0.9220

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 079/150 train_loss=0.1054 val_mAP50-95=0.7198 val_mAP50=0.9234

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 080/150 train_loss=0.1045 val_mAP50-95=0.7199 val_mAP50=0.9246

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 081/150 train_loss=0.1044 val_mAP50-95=0.7204 val_mAP50=0.9241

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 082/150 train_loss=0.1031 val_mAP50-95=0.7190 val_mAP50=0.9237

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 083/150 train_loss=0.1013 val_mAP50-95=0.7191 val_mAP50=0.9251

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 084/150 train_loss=0.1031 val_mAP50-95=0.7180 val_mAP50=0.9226

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 085/150 train_loss=0.1028 val_mAP50-95=0.7192 val_mAP50=0.9238

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 086/150 train_loss=0.1008 val_mAP50-95=0.7169 val_mAP50=0.9236

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 087/150 train_loss=0.0991 val_mAP50-95=0.7184 val_mAP50=0.9234

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 088/150 train_loss=0.0992 val_mAP50-95=0.7173 val_mAP50=0.9242

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed1] epoch 089/150 train_loss=0.0990 val_mAP50-95=0.7160 val_mAP50=0.9222
[efficientdet_d0_seed1] early stopping at epoch 89; best_epoch=69 best_val_mAP50-95=0.7207

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 001/150 train_loss=1.3597 val_mAP50-95=0.1225 val_mAP50=0.2504

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 002/150 train_loss=1.0813 val_mAP50-95=0.2222 val_mAP50=0.3695

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 003/150 train_loss=0.9308 val_mAP50-95=0.2739 val_mAP50=0.4296

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 004/150 train_loss=0.8073 val_mAP50-95=0.3274 val_mAP50=0.5016

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 005/150 train_loss=0.7228 val_mAP50-95=0.3930 val_mAP50=0.5673

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 006/150 train_loss=0.6458 val_mAP50-95=0.4519 val_mAP50=0.6446

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 007/150 train_loss=0.5837 val_mAP50-95=0.4852 val_mAP50=0.6909

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 008/150 train_loss=0.5352 val_mAP50-95=0.5308 val_mAP50=0.7464

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 009/150 train_loss=0.4917 val_mAP50-95=0.5844 val_mAP50=0.7970

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 010/150 train_loss=0.4534 val_mAP50-95=0.6094 val_mAP50=0.8315

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 011/150 train_loss=0.4150 val_mAP50-95=0.6256 val_mAP50=0.8487

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 012/150 train_loss=0.3904 val_mAP50-95=0.6276 val_mAP50=0.8615

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 013/150 train_loss=0.3668 val_mAP50-95=0.6473 val_mAP50=0.8719

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 014/150 train_loss=0.3445 val_mAP50-95=0.6600 val_mAP50=0.8784

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 015/150 train_loss=0.3266 val_mAP50-95=0.6642 val_mAP50=0.8842

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 016/150 train_loss=0.3109 val_mAP50-95=0.6709 val_mAP50=0.8937

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 017/150 train_loss=0.2934 val_mAP50-95=0.6761 val_mAP50=0.8962

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 018/150 train_loss=0.2844 val_mAP50-95=0.6741 val_mAP50=0.9002

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 019/150 train_loss=0.2735 val_mAP50-95=0.6855 val_mAP50=0.9049

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 020/150 train_loss=0.2615 val_mAP50-95=0.6889 val_mAP50=0.9030

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 021/150 train_loss=0.2539 val_mAP50-95=0.6923 val_mAP50=0.9034

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 022/150 train_loss=0.2458 val_mAP50-95=0.6979 val_mAP50=0.9087

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 023/150 train_loss=0.2388 val_mAP50-95=0.6990 val_mAP50=0.9107

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 024/150 train_loss=0.2293 val_mAP50-95=0.6992 val_mAP50=0.9122

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 025/150 train_loss=0.2191 val_mAP50-95=0.7002 val_mAP50=0.9101

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 026/150 train_loss=0.2156 val_mAP50-95=0.6995 val_mAP50=0.9078

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 027/150 train_loss=0.2144 val_mAP50-95=0.7041 val_mAP50=0.9098

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 028/150 train_loss=0.2054 val_mAP50-95=0.6976 val_mAP50=0.9153

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 029/150 train_loss=0.2037 val_mAP50-95=0.6996 val_mAP50=0.9126

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 030/150 train_loss=0.1970 val_mAP50-95=0.7081 val_mAP50=0.9194

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 031/150 train_loss=0.1935 val_mAP50-95=0.7047 val_mAP50=0.9141

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 032/150 train_loss=0.1909 val_mAP50-95=0.7110 val_mAP50=0.9207

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 033/150 train_loss=0.1861 val_mAP50-95=0.7045 val_mAP50=0.9163

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 034/150 train_loss=0.1834 val_mAP50-95=0.7041 val_mAP50=0.9116

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 035/150 train_loss=0.1807 val_mAP50-95=0.7059 val_mAP50=0.9147

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 036/150 train_loss=0.1724 val_mAP50-95=0.7069 val_mAP50=0.9124

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 037/150 train_loss=0.1706 val_mAP50-95=0.7025 val_mAP50=0.9107

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 038/150 train_loss=0.1690 val_mAP50-95=0.7065 val_mAP50=0.9183

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 039/150 train_loss=0.1655 val_mAP50-95=0.7057 val_mAP50=0.9147

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 040/150 train_loss=0.1619 val_mAP50-95=0.7153 val_mAP50=0.9209

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 041/150 train_loss=0.1597 val_mAP50-95=0.7144 val_mAP50=0.9207

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 042/150 train_loss=0.1555 val_mAP50-95=0.7101 val_mAP50=0.9204

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 043/150 train_loss=0.1565 val_mAP50-95=0.7128 val_mAP50=0.9215

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 044/150 train_loss=0.1525 val_mAP50-95=0.7115 val_mAP50=0.9192

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 045/150 train_loss=0.1506 val_mAP50-95=0.7148 val_mAP50=0.9220

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 046/150 train_loss=0.1476 val_mAP50-95=0.7152 val_mAP50=0.9196

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 047/150 train_loss=0.1417 val_mAP50-95=0.7126 val_mAP50=0.9184

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 048/150 train_loss=0.1409 val_mAP50-95=0.7137 val_mAP50=0.9185

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 049/150 train_loss=0.1399 val_mAP50-95=0.7119 val_mAP50=0.9175

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 050/150 train_loss=0.1420 val_mAP50-95=0.7192 val_mAP50=0.9229

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 051/150 train_loss=0.1370 val_mAP50-95=0.7181 val_mAP50=0.9234

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 052/150 train_loss=0.1361 val_mAP50-95=0.7202 val_mAP50=0.9251

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 053/150 train_loss=0.1330 val_mAP50-95=0.7142 val_mAP50=0.9265

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 054/150 train_loss=0.1332 val_mAP50-95=0.7194 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 055/150 train_loss=0.1303 val_mAP50-95=0.7130 val_mAP50=0.9208

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 056/150 train_loss=0.1284 val_mAP50-95=0.7131 val_mAP50=0.9190

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 057/150 train_loss=0.1270 val_mAP50-95=0.7172 val_mAP50=0.9209

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 058/150 train_loss=0.1255 val_mAP50-95=0.7118 val_mAP50=0.9209

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 059/150 train_loss=0.1245 val_mAP50-95=0.7172 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 060/150 train_loss=0.1234 val_mAP50-95=0.7177 val_mAP50=0.9198

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 061/150 train_loss=0.1207 val_mAP50-95=0.7200 val_mAP50=0.9176

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 062/150 train_loss=0.1196 val_mAP50-95=0.7149 val_mAP50=0.9162

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 063/150 train_loss=0.1155 val_mAP50-95=0.7214 val_mAP50=0.9215

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 064/150 train_loss=0.1144 val_mAP50-95=0.7177 val_mAP50=0.9248

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 065/150 train_loss=0.1150 val_mAP50-95=0.7194 val_mAP50=0.9216

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 066/150 train_loss=0.1127 val_mAP50-95=0.7193 val_mAP50=0.9250

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 067/150 train_loss=0.1127 val_mAP50-95=0.7139 val_mAP50=0.9204

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 068/150 train_loss=0.1118 val_mAP50-95=0.7164 val_mAP50=0.9225

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 069/150 train_loss=0.1096 val_mAP50-95=0.7166 val_mAP50=0.9221

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 070/150 train_loss=0.1094 val_mAP50-95=0.7158 val_mAP50=0.9183

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 071/150 train_loss=0.1073 val_mAP50-95=0.7191 val_mAP50=0.9223

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 072/150 train_loss=0.1073 val_mAP50-95=0.7198 val_mAP50=0.9213

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 073/150 train_loss=0.1074 val_mAP50-95=0.7206 val_mAP50=0.9259

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 074/150 train_loss=0.1052 val_mAP50-95=0.7203 val_mAP50=0.9257

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 075/150 train_loss=0.1044 val_mAP50-95=0.7198 val_mAP50=0.9274

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 076/150 train_loss=0.1030 val_mAP50-95=0.7201 val_mAP50=0.9245

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 077/150 train_loss=0.1042 val_mAP50-95=0.7174 val_mAP50=0.9199

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 078/150 train_loss=0.1027 val_mAP50-95=0.7188 val_mAP50=0.9242

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 079/150 train_loss=0.1010 val_mAP50-95=0.7162 val_mAP50=0.9262

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 080/150 train_loss=0.0998 val_mAP50-95=0.7209 val_mAP50=0.9257

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 081/150 train_loss=0.1006 val_mAP50-95=0.7177 val_mAP50=0.9249

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 082/150 train_loss=0.0970 val_mAP50-95=0.7199 val_mAP50=0.9243

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

[efficientdet_d0_seed2] epoch 083/150 train_loss=0.0978 val_mAP50-95=0.7185 val_mAP50=0.9220
[efficientdet_d0_seed2] early stopping at epoch 83; best_epoch=63 best_val_mAP50-95=0.7214

WARNING:timm.models._builder:Unexpected keys (bn2.num_batches_tracked, bn2.bias, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.

,model,seed,run,best_epoch,best_val_mAP50-95,precision,recall,mAP50,mAP50-95,inference_ms
0,EfficientDet-D0,0,efficientdet_d0_seed0,100,0.731596,0.030990,0.978125,0.900497,0.692968,15.882019
1,EfficientDet-D0,1,efficientdet_d0_seed1,69,0.720706,0.030891,0.975000,0.888401,0.671769,10.755861
2,EfficientDet-D0,2,efficientdet_d0_seed2,63,0.721444,0.030891,0.975000,0.898287,0.690050,10.882426

## RT-DETR Training And Evaluation

In [16]:
from ultralytics import RTDETR


def train_rtdetr(seed: int):
    set_seed(seed)
    run_name = f'rtdetr_l_seed{seed}'
    print(f'========== TRAIN RT-DETR | seed={seed} | run={run_name} ==========')

    model = RTDETR('rtdetr-l.pt')
    model.train(
        data=str(YOLO_DATA_YAML),
        epochs=EPOCHS,
        imgsz=IMG_SIZE,
        batch=BATCH_SIZE,
        nbs=EFFECTIVE_BATCH_SIZE,
        patience=20,
        project=str(OUTPUT_ROOT),
        name=run_name,
        device=0 if DEVICE == 'cuda' else 'cpu',
        seed=seed,
        deterministic=True,
    )

    model_path = OUTPUT_ROOT / run_name / 'weights' / 'best.pt'
    model = RTDETR(str(model_path))
    metrics = model.val(
        data=str(YOLO_DATA_YAML),
        split='test',
        imgsz=IMG_SIZE,
        batch=BATCH_SIZE,
        device=0 if DEVICE == 'cuda' else 'cpu',
        verbose=False,
    )
    row = {
        'model': 'RT-DETR-L',
        'seed': seed,
        'run': run_name,
        'best_epoch': np.nan,
        'best_val_mAP50-95': np.nan,
        'precision': float(metrics.box.mp),
        'recall': float(metrics.box.mr),
        'mAP50': float(metrics.box.map50),
        'mAP50-95': float(metrics.box.map),
        'preprocess_ms': float(metrics.speed.get('preprocess', 0.0)),
        'inference_ms': float(metrics.speed.get('inference', 0.0)),
        'postprocess_ms': float(metrics.speed.get('postprocess', 0.0)),
    }
    save_run_result(OUTPUT_ROOT / run_name, row)
    return row


rtdetr_rows = []
for seed in SEEDS:
    rtdetr_rows.append(train_rtdetr(seed))

pd.DataFrame(rtdetr_rows)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
========== TRAIN RT-DETR | seed=0 | run=rtdetr_l_seed0 ==========
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/rtdetr-l.pt to 'rtdetr-l.pt': 100% ━━━━━━━━━━━━ 63.4MB 40.6MB/s 1.6s
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/data/data/tom_benh.v1i.yolov11/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=rtdetr_l_seed0, nbs=32, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp/runs_detection_models, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 131.0MB/s 0.0s
Overriding model.yaml nc=80 with nc=2
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7305962  ultralytics.nn.modules.head.RTDETRDecoder    [2, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,810,186 parameters, 32,810,186 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 287.3MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1100.6±477.6 MB/s, size: 30.9 KB)
train: Scanning /content/data/data/tom_benh.v1i.yolov11/train/labels... 707 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 707/707 1.2Kit/s 0.6s
train: New cache created: /content/data/data/tom_benh.v1i.yolov11/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 873.4±620.4 MB/s, size: 32.5 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/valid/labels... 202 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 202/202 914.7it/s 0.2s
val: New cache created: /content/data/data/tom_benh.v1i.yolov11/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0/labels.jpg...
Image sizes 512 train, 512 val
Using 8 dataloader workers
Logging results to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0
Starting training for 150 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      1/150       6.4G      1.755      1.025      1.547         54        512: 0% ──────────── 0/177  5.2s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      1/150      6.56G      0.558     0.8893     0.4512         27        512: 100% ━━━━━━━━━━━━ 177/177 2.8it/s 1:03
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 4.9it/s 5.3s
                   all        202        660      0.818      0.747      0.829      0.682

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      2/150      6.68G     0.5575     0.3754     0.3454         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      2/150      6.68G     0.3485     0.5823      0.228         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.763      0.711      0.783      0.601

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      3/150      6.68G     0.2968     0.5285     0.1897         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      3/150      6.68G     0.3286     0.5918     0.2138         11        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.664      0.322      0.347      0.262

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      4/150      6.68G     0.3589     0.5117     0.2876         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      4/150      6.68G     0.3476     0.5808     0.2254         22        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.814      0.782       0.86      0.709

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      5/150      6.68G      0.232     0.5009     0.1606         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      5/150      6.68G     0.3046      0.583     0.1894         24        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.567      0.636      0.569      0.461

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      6/150      6.68G     0.2713     0.6411     0.1368         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      6/150      6.68G     0.3085     0.5967     0.1988         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.4it/s 2.3s
                   all        202        660      0.722      0.746      0.773      0.652

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      7/150      6.68G     0.4035     0.4667     0.1927         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      7/150      6.68G     0.3105     0.5949     0.1976         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.7it/s 2.2s
                   all        202        660      0.763      0.457      0.479      0.398

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      8/150      6.68G     0.1584     0.4972     0.1557         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      8/150      6.68G     0.2995     0.5782     0.1853         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.866      0.788      0.863       0.73

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      9/150      6.68G     0.2546     0.5755     0.1221         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      9/150      6.68G     0.2904      0.533     0.1788         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.759      0.698      0.733       0.61

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     10/150      6.68G     0.3322     0.5215      0.172         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     10/150      6.69G     0.2948     0.5492     0.1832         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.885      0.723      0.771       0.66

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     11/150      6.69G     0.3174     0.4449     0.1601         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     11/150      6.69G     0.2735     0.5168      0.174         11        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.874      0.812      0.875      0.746

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     12/150      6.69G     0.2579     0.5316     0.1951         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     12/150      6.69G     0.2729     0.5218     0.1679         10        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.4it/s 2.3s
                   all        202        660       0.87      0.756      0.814      0.687

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     13/150      6.69G     0.3565      0.449     0.1928         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     13/150      6.69G     0.2667     0.5284     0.1732          8        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.842      0.749      0.791      0.659

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     14/150      6.69G     0.2288     0.5434      0.121         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     14/150      6.69G     0.2673     0.5191     0.1641         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.857      0.812      0.869      0.733

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     15/150      6.69G     0.3535      0.395     0.1897         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     15/150      6.69G     0.2577     0.4945     0.1609         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.868      0.805      0.871      0.748

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     16/150      6.69G     0.2883      0.352     0.1668         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     16/150      6.69G     0.2569     0.4872     0.1597         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.4it/s 2.3s
                   all        202        660      0.858      0.821      0.878      0.761

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     17/150      6.69G      0.221     0.3499     0.1486         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     17/150      6.69G     0.2489     0.4934     0.1532         20        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.891      0.861      0.913      0.796

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     18/150      6.69G     0.2451     0.3858     0.1477         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     18/150      6.69G     0.2582     0.4846     0.1566          9        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.5it/s 2.3s
                   all        202        660      0.859      0.724       0.77      0.662

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     19/150      6.69G     0.4272     0.4876     0.2127         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     19/150      6.69G     0.2344     0.4595     0.1435         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.877      0.814      0.863      0.745

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     20/150      6.69G     0.3296     0.5561      0.171         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     20/150      6.69G     0.2483     0.4681     0.1515         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.879      0.856      0.921      0.792

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     21/150      6.69G     0.2353     0.2965     0.1782         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     21/150      6.69G     0.2416     0.4515     0.1488         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.4it/s 2.3s
                   all        202        660      0.775      0.686      0.718      0.615

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     22/150      6.69G     0.2512     0.4158     0.1129         36        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     22/150      6.69G     0.2448     0.4628     0.1509         12        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.888      0.887      0.931        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     23/150      6.69G     0.3384     0.4502     0.1772         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     23/150      6.69G     0.2402     0.4582     0.1456         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.903      0.856      0.911      0.799

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     24/150      6.69G     0.1692     0.3145     0.1107         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     24/150      6.69G     0.2404     0.4525     0.1424         27        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.89      0.877      0.921      0.803

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     25/150      6.69G        0.2      0.461     0.1269         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     25/150      6.69G     0.2381     0.4599     0.1473         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.894      0.848      0.917      0.797

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     26/150      6.69G     0.2999      0.557     0.1482         48        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     26/150      6.69G     0.2331     0.4429     0.1415         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660        0.9      0.866      0.926      0.808

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     27/150      6.69G     0.1901      0.422    0.08343         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     27/150      6.69G     0.2277      0.444      0.138         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.872      0.858      0.909      0.787

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     28/150      6.69G     0.1672     0.5051    0.08186         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     28/150      6.69G     0.2207     0.4482     0.1348         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.861      0.853      0.899      0.778

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     29/150      6.69G     0.1784     0.6126    0.07336         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     29/150      6.69G     0.2173     0.4292     0.1336         31        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.869      0.874      0.925      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     30/150      6.69G     0.1932     0.3436    0.07421         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     30/150      6.69G     0.2302     0.4356     0.1442         28        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.874      0.859      0.911        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     31/150      6.69G     0.3149     0.5803     0.2056         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     31/150      6.69G     0.2361     0.4505     0.1497         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.869      0.772      0.861      0.729

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     32/150      6.69G     0.1766     0.3765     0.1199         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     32/150      6.69G     0.2265     0.4474     0.1357         11        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.895      0.875      0.937       0.82

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     33/150      6.69G     0.1468     0.3763     0.1279         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     33/150      6.69G     0.2278     0.4473      0.134          9        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.891      0.882       0.93      0.805

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     34/150      6.69G     0.1578     0.3334     0.1129         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     34/150      6.69G      0.227     0.4441     0.1404         14        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.867      0.903      0.928       0.81

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     35/150      6.69G     0.3506     0.4042     0.2032         29        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     35/150      6.69G     0.2271     0.4463      0.135         22        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.845      0.829      0.891      0.776

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     36/150      6.69G     0.2189     0.4189     0.1045         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     36/150      6.69G     0.2271     0.4486     0.1339         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.833      0.876      0.914      0.801

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     37/150      6.69G     0.2759     0.5145     0.1389         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     37/150      6.69G      0.227     0.4322     0.1404         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.883       0.85      0.915      0.799

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     38/150      6.69G     0.2258     0.4051     0.1062         35        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     38/150      6.69G     0.2396     0.4453     0.1452         10        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.896      0.854      0.916      0.793

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     39/150      6.69G     0.2745     0.4435     0.1636         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     39/150      6.69G     0.2545       0.49     0.1584         13        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.863      0.813      0.886      0.764

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     40/150      6.69G     0.2187      0.625      0.156         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     40/150      6.69G     0.2292     0.4562      0.142         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.872      0.858      0.902      0.786

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     41/150      6.69G     0.2232     0.5281    0.09936         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     41/150      6.69G     0.2267     0.4425     0.1346         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.885      0.868      0.909        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     42/150      6.69G     0.2064     0.4466     0.1568         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     42/150      6.69G     0.2266      0.433     0.1371         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.889      0.884      0.925      0.809

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     43/150      6.69G     0.2984     0.4169     0.1497         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     43/150      6.69G     0.2181     0.4317     0.1306         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.905      0.856      0.917      0.798

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     44/150      6.69G     0.1257      0.279    0.07553         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     44/150      6.69G     0.2161     0.4199     0.1335         12        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.893      0.874      0.934      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     45/150      6.69G     0.3122     0.6621     0.1991         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     45/150      6.69G     0.2109     0.4227     0.1267         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.901      0.879      0.928      0.815

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     46/150      6.69G      0.172      0.446     0.1727         12        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     46/150      6.69G     0.2186     0.4178     0.1315         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.905      0.891      0.921      0.806

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     47/150      6.69G     0.2019     0.6613     0.1198         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     47/150      6.69G     0.2136      0.401     0.1279         12        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660       0.92      0.874      0.937      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     48/150      6.69G     0.1661     0.4614     0.1194         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     48/150      6.69G     0.2176     0.4142     0.1374         25        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.892      0.894      0.926      0.806

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     49/150      6.69G     0.1497     0.4558    0.08741         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     49/150      6.69G     0.2194     0.4103     0.1315          9        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.897       0.89      0.926      0.816

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     50/150      6.69G     0.2638      0.371     0.1319         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     50/150      6.69G     0.2064     0.3978     0.1243         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.885      0.881      0.915      0.807

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     51/150      6.69G     0.2217      0.377     0.1101         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     51/150      6.69G     0.2043     0.3861     0.1197         13        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.912       0.87      0.931      0.819

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     52/150      6.69G     0.1222     0.3365     0.1398         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     52/150      6.69G     0.2081      0.406     0.1256         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.893      0.889      0.926      0.814

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     53/150      6.69G     0.1707     0.3523     0.1196         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     53/150      6.69G     0.2019     0.3923      0.122         26        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.894      0.896      0.932      0.824

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     54/150      6.69G     0.1279     0.3947    0.07635         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     54/150      6.69G     0.1975     0.3849     0.1195          9        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.88      0.913      0.932       0.82

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     55/150      6.69G     0.2735     0.3738     0.1124         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     55/150      6.69G     0.2064     0.3808     0.1218         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.906      0.889      0.933      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     56/150      6.69G      0.182     0.3065      0.107         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     56/150      6.69G     0.1968     0.3722     0.1142         33        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.891      0.913      0.931      0.819

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     57/150      6.69G     0.2452     0.3433     0.1482         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     57/150      6.69G      0.195     0.3859      0.114         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660       0.88      0.889      0.919      0.804

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     58/150      6.69G     0.1982     0.3329     0.1183         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     58/150      6.69G     0.1874     0.3648     0.1088         13        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.894      0.872      0.919      0.804

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     59/150      6.69G     0.2553     0.4642     0.1443         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     59/150      6.69G     0.1896      0.375     0.1108         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.897      0.903      0.944      0.837

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     60/150      6.69G     0.1253     0.3802    0.06638         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     60/150      6.69G     0.1916      0.377     0.1146         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.914      0.902      0.941      0.834

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     61/150      6.69G     0.1931     0.3086     0.1119         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     61/150      6.69G     0.1892     0.3578     0.1134         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.878      0.891      0.926      0.825

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     62/150      6.69G     0.1509     0.3629    0.06956         35        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     62/150      6.69G     0.1977     0.3755     0.1162         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.887      0.891      0.938       0.83

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     63/150      6.69G     0.2143     0.3919     0.1324         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     63/150      6.69G     0.1851     0.3557     0.1094         28        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.894      0.896      0.945      0.833

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     64/150      6.69G    0.08914     0.3081    0.05545         10        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     64/150      6.69G     0.1913     0.3543     0.1119         24        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.911      0.896      0.942      0.839

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     65/150      6.69G     0.1798     0.3091    0.08057         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     65/150      6.69G       0.19     0.3589     0.1076         30        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.913      0.901      0.939      0.841

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     66/150      6.69G     0.2529     0.2926     0.1662         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     66/150      6.69G     0.1842     0.3474     0.1085         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.894      0.906      0.936      0.827

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     67/150      6.69G      0.228     0.3271     0.1129         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     67/150      6.69G     0.1874     0.3619     0.1091         25        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.884      0.913      0.934      0.825

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     68/150      6.69G     0.1333     0.4226    0.09859         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     68/150      6.69G     0.1888     0.3556     0.1064         14        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.894      0.905      0.928       0.82

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     69/150      6.69G     0.1546     0.3848    0.08326         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     69/150      6.69G     0.1797     0.3433     0.1064         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.908       0.91      0.942      0.834

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     70/150      6.69G     0.1988     0.3445    0.09219         14        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     70/150      6.69G     0.1881     0.3575     0.1102          8        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.892      0.905       0.94      0.831

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     71/150      6.69G     0.2741     0.4222     0.1373         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     71/150      6.69G     0.1923     0.3609      0.113         11        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.904      0.908      0.936       0.83

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     72/150      6.69G    0.09392     0.2471    0.06724         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     72/150      6.69G     0.1914     0.3571     0.1112         20        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.893      0.907      0.937      0.834

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     73/150      6.69G     0.2976     0.3333     0.2815         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     73/150      6.69G      0.186     0.3467     0.1093         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.889      0.902      0.937      0.832

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     74/150      6.69G     0.1852     0.2698    0.08988         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     74/150      6.69G     0.1849     0.3438     0.1101         27        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.891      0.902       0.93       0.83

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     75/150      6.69G       0.23      0.362     0.1083         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     75/150      6.69G     0.1726     0.3379     0.1048          9        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.918      0.893      0.933      0.832

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     76/150      6.69G       0.19     0.4085      0.125         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     76/150      6.69G     0.1811     0.3519     0.1054         24        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660        0.9      0.891      0.933      0.834

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     77/150      6.69G     0.2139     0.3839    0.09709         36        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     77/150      6.69G     0.1759     0.3346     0.1025         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660       0.89      0.894      0.936      0.837

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     78/150      6.69G     0.1442     0.3133    0.07912         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     78/150      6.69G     0.1777     0.3472     0.1034         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.908      0.893      0.942       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     79/150      6.69G     0.2143      0.594     0.2388         11        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     79/150      6.69G     0.1815     0.3569     0.1058         28        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.892       0.88      0.933       0.83

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     80/150      6.69G     0.1402     0.3364     0.1143         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     80/150      6.69G     0.1789     0.3322     0.1081         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.901      0.882      0.934      0.832

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     81/150      6.69G     0.1262     0.2384     0.0995         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     81/150      6.69G     0.1743     0.3294     0.1002         30        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.923      0.894      0.937      0.835

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     82/150      6.69G     0.1791     0.3389    0.08395         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     82/150      6.69G     0.1703     0.3247     0.1007         21        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.902      0.895      0.945      0.844

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     83/150      6.69G     0.1163     0.3467    0.08144         15        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     83/150      6.69G     0.1659     0.3184    0.09823         19        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.893      0.897      0.939      0.839

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     84/150      6.69G     0.2117     0.4612     0.1276         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     84/150      6.69G     0.1675     0.3118     0.0995         26        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 51.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.914      0.915      0.945      0.843

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     85/150      6.69G     0.2968     0.3359     0.1149         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     85/150      6.69G     0.1728     0.3298    0.09747         13        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.913      0.896       0.94      0.842

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     86/150      6.69G     0.1222     0.2924    0.06934         40        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     86/150      6.69G     0.1632     0.3191    0.09751         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.914      0.899      0.943      0.841

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     87/150      6.69G     0.1466     0.3313    0.08303         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     87/150      6.69G     0.1731     0.3232    0.09857         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.903      0.894      0.937      0.841

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     88/150      6.69G     0.1978     0.3071     0.1347         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     88/150      6.69G     0.1739     0.3334    0.09795         12        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.907      0.891       0.95      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     89/150      6.69G     0.1987     0.3863     0.1038         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     89/150      6.69G     0.1671     0.3302    0.09688         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660       0.91      0.901      0.945      0.839

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     90/150      6.69G      0.164     0.4278     0.1178         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     90/150      6.69G     0.1615     0.3137    0.09104         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.906      0.904      0.946      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     91/150      6.69G     0.1188     0.2429    0.09423         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     91/150      6.69G     0.1653     0.3146    0.09473         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.898      0.914      0.945      0.847

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     92/150      6.69G     0.1519     0.2521    0.08395         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     92/150      6.69G     0.1654     0.3172    0.09709         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.897      0.893      0.932      0.827

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     93/150      6.69G        0.2     0.3956     0.1227         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     93/150      6.69G     0.1656     0.3124    0.09274         13        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.879      0.933      0.947      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     94/150      6.69G      0.186     0.4001     0.1172         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     94/150      6.69G     0.1639     0.3096     0.0909         24        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.917      0.901      0.946      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     95/150      6.69G     0.1079     0.2547    0.09536         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     95/150      6.69G     0.1562     0.2915    0.08725          7        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.907      0.904       0.94      0.842

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     96/150      6.69G     0.1835     0.2404     0.1284         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     96/150      6.69G     0.1625     0.2988    0.09342         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.902      0.896      0.939      0.839

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     97/150      6.69G     0.1572     0.2723    0.08172         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     97/150      6.69G     0.1499     0.2976    0.08913         20        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.915        0.9      0.943      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     98/150      6.69G      0.144     0.2973    0.06769         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     98/150      6.69G     0.1557     0.2977    0.08874         20        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.915      0.906      0.943      0.848

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     99/150      6.69G     0.1113     0.2471    0.05821         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     99/150      6.69G     0.1535     0.2912    0.08504         20        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.921      0.904      0.951      0.859

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    100/150      6.69G    0.06934     0.3364    0.04059         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    100/150      6.69G     0.1547     0.3022    0.09158         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.921      0.901      0.946      0.854

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    101/150      6.69G     0.1911     0.3198     0.0807         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    101/150      6.69G     0.1563     0.2928    0.08734         27        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.901      0.914      0.944      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    102/150      6.69G     0.1269     0.2037     0.1127         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    102/150      6.69G     0.1603     0.3008    0.09099         10        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.917      0.908       0.95      0.853

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    103/150      6.69G     0.2368      0.366    0.07362         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    103/150      6.69G     0.1572     0.2877    0.09124         22        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.909        0.9      0.951      0.855

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    104/150      6.69G     0.1385     0.2156     0.1493         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    104/150      6.69G     0.1526     0.2805    0.08511         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.914      0.899      0.944      0.848

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    105/150      6.69G       0.16      0.296    0.08955         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    105/150      6.69G     0.1469     0.2783    0.08217         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.926      0.902      0.947       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    106/150      6.69G     0.1638     0.2953     0.0865         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    106/150      6.69G     0.1549     0.2901    0.08858         15        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.906      0.906      0.939      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    107/150      6.69G     0.1147     0.3008     0.1061         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    107/150      6.69G     0.1525     0.2921    0.09012         22        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.901      0.894      0.943      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    108/150      6.69G     0.2051        0.5     0.1155         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    108/150      6.69G     0.1572     0.2937    0.09025         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.92      0.892      0.949      0.855

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    109/150      6.69G     0.1243     0.2624     0.1086         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    109/150      6.69G     0.1568     0.2849    0.08789         23        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660       0.91      0.907      0.942       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    110/150      6.69G     0.1611     0.2441       0.12         13        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    110/150      6.69G     0.1463     0.2888    0.08317         30        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.921      0.899       0.95      0.856

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    111/150      6.69G     0.1031     0.2792    0.05555         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    111/150      6.69G     0.1511     0.2815    0.08527         14        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.904      0.903      0.943      0.851

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    112/150      6.69G     0.0724     0.1582    0.06158         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    112/150      6.69G     0.1531     0.2818    0.08661         29        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.913      0.903      0.952      0.858

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    113/150      6.69G     0.1135      0.188    0.07449         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    113/150      6.69G     0.1427     0.2776    0.07982         25        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.908      0.907      0.944       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    114/150      6.69G     0.1513     0.4543      0.136         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    114/150      6.69G     0.1535     0.2932    0.08634         33        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.6it/s 2.4s
                   all        202        660      0.901      0.895      0.944      0.851

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    115/150      6.69G     0.1903     0.3001    0.08865         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    115/150      6.69G      0.144     0.2801     0.0841         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.901      0.914      0.946      0.851

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    116/150      6.69G    0.08676     0.1844    0.05603         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    116/150      6.69G     0.1462     0.2804    0.08159         18        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.921      0.895      0.954      0.858

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    117/150      6.69G     0.1397     0.3088    0.06556         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    117/150      6.69G     0.1479     0.2717    0.08319         22        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.914       0.91      0.951      0.853

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    118/150      6.69G    0.08273     0.2141    0.05481         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    118/150      6.69G     0.1395     0.2712    0.07951         17        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.902      0.907      0.945       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    119/150      6.69G    0.08708     0.3013    0.04867         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    119/150      6.69G     0.1453     0.2732    0.08199         25        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.905      0.915      0.942      0.849
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 99, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

119 epochs completed in 1.855 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0/weights/last.pt, 66.2MB
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0/weights/best.pt, 66.2MB

Validating /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0/weights/best.pt...
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.919      0.903      0.951      0.859
                     0        187        321      0.906      0.882      0.934       0.84
                     1        188        339      0.932      0.925      0.968      0.879
Speed: 0.1ms preprocess, 7.4ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed0
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1197.2±284.0 MB/s, size: 33.6 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/test/labels... 101 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 101/101 1.2Kit/s 0.1s
val: New cache created: /content/data/data/tom_benh.v1i.yolov11/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 14.7it/s 1.8s
                   all        101        320      0.883      0.876      0.911      0.801
Speed: 0.5ms preprocess, 12.1ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val
========== TRAIN RT-DETR | seed=1 | run=rtdetr_l_seed1 ==========
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/data/data/tom_benh.v1i.yolov11/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=rtdetr_l_seed1, nbs=32, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp/runs_detection_models, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=1, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7305962  ultralytics.nn.modules.head.RTDETRDecoder    [2, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,810,186 parameters, 32,810,186 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1043.1±329.3 MB/s, size: 26.7 KB)
train: Scanning /content/data/data/tom_benh.v1i.yolov11/train/labels.cache... 707 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 707/707 185.3Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 335.9±196.4 MB/s, size: 33.0 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/valid/labels.cache... 202 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 202/202 8.7Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1/labels.jpg...
Image sizes 512 train, 512 val
Using 8 dataloader workers
Logging results to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1
Starting training for 150 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      1/150      5.08G      1.299      2.278     0.8058         54        512: 0% ──────────── 0/177  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      1/150      5.44G     0.4556      1.415      0.321         27        512: 100% ━━━━━━━━━━━━ 177/177 3.2it/s 55.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.785      0.718       0.79      0.636

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      2/150      5.56G     0.3879     0.4965     0.2357         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      2/150      5.56G     0.3169     0.6172     0.2059         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 54.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.809      0.726      0.792      0.615

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      3/150      5.56G     0.3971     0.6233     0.2154         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      3/150      5.56G      0.325     0.5995     0.2111         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.812      0.782      0.853      0.701

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      4/150      5.56G     0.3106     0.5323     0.2479         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      4/150      5.56G     0.3204     0.5783     0.2003         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.811       0.79      0.848      0.692

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      5/150      5.56G     0.2017      0.444     0.1203         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      5/150      5.56G     0.3061     0.5828      0.194         24        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.798      0.741      0.817      0.673

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      6/150      5.56G     0.3001     0.6295     0.1575         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      6/150      5.56G     0.3049     0.5769     0.1975         16        512: 100% ━━━━━━━━━━━━ 177/177 3.4it/s 52.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.824      0.692      0.777      0.644

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      7/150      5.56G     0.3457     0.4762     0.1849         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      7/150      5.56G     0.3042     0.5821     0.1932         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.787      0.752      0.845      0.692

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      8/150      5.56G     0.1834     0.5043     0.1581         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      8/150      5.56G     0.2994     0.5634     0.1841         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.862      0.832      0.896      0.755

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      9/150      5.56G     0.2382     0.6393     0.1097         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      9/150      5.56G     0.2811     0.5397     0.1726         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.867      0.824       0.89      0.749

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     10/150      5.56G     0.3257     0.5587     0.1801         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     10/150      5.56G     0.2809     0.5324     0.1742         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.84       0.82       0.88      0.739

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     11/150      5.56G      0.364       0.54     0.1852         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     11/150      5.56G     0.2729     0.5581     0.1758         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.889      0.787      0.878      0.734

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     12/150      5.56G     0.2595      0.561     0.1041         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     12/150      5.56G     0.2804     0.5553     0.1742         10        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.851      0.797      0.882      0.734

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     13/150      5.56G     0.3796     0.5363     0.2274         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     13/150      5.56G     0.2701     0.5273     0.1763          8        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.848       0.84      0.876      0.746

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     14/150      5.56G     0.3115     0.4562     0.2068         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     14/150      5.56G     0.2629     0.5275     0.1651         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.833      0.847       0.89      0.753

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     15/150      5.56G     0.2208      0.355     0.1175         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     15/150      5.56G     0.2488     0.4906     0.1528         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.859      0.849      0.895      0.766

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     16/150      5.56G     0.2073     0.3948      0.135         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     16/150      5.56G     0.2399     0.4793     0.1472         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.854      0.838      0.897      0.779

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     17/150      5.56G     0.2068      0.392     0.1251         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     17/150      5.56G     0.2404     0.4713     0.1473         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.901      0.888      0.937      0.821

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     18/150      5.56G     0.1983     0.3416     0.1115         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     18/150      5.56G     0.2518     0.4769     0.1471          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.862      0.879       0.92       0.79

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     19/150      5.56G     0.2721       0.58    0.09895         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     19/150      5.56G     0.2376     0.4751     0.1473         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.853       0.86      0.916      0.783

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     20/150      5.56G     0.3354     0.4391     0.1904         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     20/150      5.56G     0.2457     0.4801     0.1514         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.858      0.847      0.896      0.755

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     21/150      5.56G     0.2451     0.2772     0.1714         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     21/150      5.56G     0.2434     0.4648     0.1508         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.904      0.861      0.917        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     22/150      5.56G     0.3176     0.4224     0.1539         36        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     22/150      5.56G     0.2429     0.4665     0.1495         12        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.907      0.861       0.91      0.792

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     23/150      5.56G     0.3664     0.4834     0.2211         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     23/150      5.56G     0.2324     0.4538     0.1394         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.888      0.887      0.933      0.817

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     24/150      5.56G     0.1508     0.3596    0.08936         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     24/150      5.56G     0.2356     0.4484     0.1371         27        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.893       0.84      0.917      0.793

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     25/150      5.56G     0.2519     0.4994     0.1875         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     25/150      5.56G     0.2306     0.4473     0.1436         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.902      0.875      0.918      0.801

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     26/150      5.56G     0.2913     0.5835      0.139         48        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     26/150      5.56G     0.2292     0.4446     0.1377         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.875       0.87      0.916        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     27/150      5.56G     0.1781     0.3956     0.0771         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     27/150      5.56G     0.2338     0.4444     0.1448         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.877       0.84      0.899      0.776

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     28/150      5.56G       0.21     0.5276     0.1285         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     28/150      5.56G     0.2346     0.4573     0.1462         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.885      0.879      0.926      0.808

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     29/150      5.56G     0.1947     0.6108    0.08697         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     29/150      5.56G     0.2286     0.4471     0.1447         31        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.901      0.874      0.925      0.806

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     30/150      5.56G     0.2162     0.3459    0.09566         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     30/150      5.56G     0.2401     0.4406     0.1527         28        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.851      0.861      0.897      0.784

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     31/150      5.56G     0.3045     0.5799      0.217         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     31/150      5.56G      0.236     0.4647     0.1501         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.854      0.868       0.92      0.794

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     32/150      5.56G     0.1671     0.4533     0.1002         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     32/150      5.56G     0.2398     0.4814     0.1499         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.87      0.882      0.915      0.789

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     33/150      5.56G     0.2023     0.3424     0.1411         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     33/150      5.56G     0.2286     0.4713     0.1381          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.874      0.838      0.899      0.765

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     34/150      5.56G     0.1516      0.355     0.1149         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     34/150      5.56G     0.2415      0.478     0.1516         14        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 52.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.887      0.887      0.917        0.8

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     35/150      5.56G     0.2926     0.3733      0.124         29        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     35/150      5.56G     0.2365     0.4719     0.1434         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.877      0.818      0.888      0.769

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     36/150      5.56G     0.2575     0.4064     0.1319         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     36/150      5.56G     0.2349     0.4613      0.142         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.903      0.871      0.931      0.804

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     37/150      5.56G     0.2453     0.4555    0.09928         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     37/150      5.56G     0.2219     0.4451     0.1359         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.6it/s 2.5s
                   all        202        660        0.9      0.888       0.93      0.812
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 17, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

37 epochs completed in 0.588 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1/weights/last.pt, 66.2MB
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1/weights/best.pt, 66.2MB

Validating /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1/weights/best.pt...
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.899      0.888      0.937       0.82
                     0        187        321      0.859      0.852      0.912      0.787
                     1        188        339       0.94      0.924      0.961      0.852
Speed: 0.1ms preprocess, 7.4ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed1
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1145.5±311.6 MB/s, size: 29.7 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/test/labels.cache... 101 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 101/101 35.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 14.9it/s 1.7s
                   all        101        320      0.862      0.843       0.88       0.76
Speed: 0.6ms preprocess, 11.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-2
========== TRAIN RT-DETR | seed=2 | run=rtdetr_l_seed2 ==========
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/data/data/tom_benh.v1i.yolov11/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=rtdetr_l_seed2, nbs=32, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp/runs_detection_models, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=2, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7305962  ultralytics.nn.modules.head.RTDETRDecoder    [2, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,810,186 parameters, 32,810,186 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1068.0±365.1 MB/s, size: 27.2 KB)
train: Scanning /content/data/data/tom_benh.v1i.yolov11/train/labels.cache... 707 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 707/707 211.8Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 117.2±51.9 MB/s, size: 30.2 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/valid/labels.cache... 202 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 202/202 11.1Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2/labels.jpg...
Image sizes 512 train, 512 val
Using 8 dataloader workers
Logging results to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2
Starting training for 150 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      1/150      5.19G     0.3849      1.559     0.2573         27        512: 100% ━━━━━━━━━━━━ 177/177 3.1it/s 57.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.744      0.756      0.764      0.615

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      2/150      5.31G     0.4224     0.4281     0.2066         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      2/150      5.31G      0.319     0.6084     0.2055         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 54.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.764      0.727      0.786      0.613

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      3/150      5.31G      0.305     0.5261     0.1772         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      3/150      5.31G     0.3192     0.6147     0.2102         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.759      0.739      0.806      0.636

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      4/150      5.31G     0.2953     0.6479       0.21         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      4/150      5.31G     0.3574      0.668     0.2346         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.805      0.699      0.816       0.65

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      5/150      5.31G     0.2487     0.4937     0.1487         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      5/150      5.31G     0.3243     0.6394     0.2088         24        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.6it/s 2.5s
                   all        202        660      0.774      0.719      0.813      0.661

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      6/150      5.31G     0.3411     0.5762     0.1917         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      6/150      5.31G     0.3253     0.6076     0.2123         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.779      0.791      0.833       0.67

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      7/150      5.31G     0.3869     0.4921     0.2467         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      7/150      5.31G     0.3254     0.5929     0.2099         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.809      0.781      0.854      0.706

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      8/150      5.31G     0.1722      0.749     0.1712         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      8/150      5.31G     0.3024     0.5623     0.1902         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.852      0.804       0.89      0.751

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      9/150      5.31G     0.2776     0.6102     0.1269         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      9/150      5.31G     0.3013     0.5754     0.1854         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.714      0.706      0.753      0.625

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     10/150      5.31G     0.2577     0.6766       0.18         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     10/150      5.31G     0.2872     0.5481     0.1798         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 54.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.857      0.838      0.899      0.759

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     11/150      5.31G     0.3622     0.4762     0.1853         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     11/150      5.31G     0.2752     0.5317     0.1753         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.744      0.683      0.733      0.609

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     12/150      5.31G     0.3106     0.4418     0.1732         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     12/150      5.31G     0.2726     0.5452     0.1683         10        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660       0.86      0.836      0.902      0.767

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     13/150      5.31G     0.3039     0.4665     0.1842         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     13/150      5.31G     0.2704     0.5367     0.1762          8        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660       0.85      0.833       0.89      0.749

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     14/150      5.31G     0.2876     0.4223     0.1697         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     14/150      5.31G     0.2582     0.5148     0.1581         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.861      0.827        0.9      0.772

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     15/150      5.31G     0.2537     0.4641     0.1414         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     15/150      5.31G     0.2656     0.5069     0.1673         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.853      0.826      0.885      0.757

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     16/150      5.31G     0.2979     0.4809     0.1893         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     16/150      5.31G     0.2534     0.4974     0.1551         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.6it/s 2.4s
                   all        202        660      0.853      0.842      0.895      0.765

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     17/150      5.31G     0.1777     0.4322     0.1146         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     17/150      5.31G     0.2468     0.5004     0.1523         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.876      0.885      0.913      0.778

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     18/150      5.31G     0.2798      0.368     0.1733         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     18/150      5.31G     0.2599     0.4909     0.1575          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.854      0.846      0.893      0.774

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     19/150      5.31G     0.2949     0.4965      0.118         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     19/150      5.31G     0.2324     0.4595     0.1455         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.873      0.885      0.917      0.793

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     20/150      5.31G     0.2688     0.4352     0.1909         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     20/150      5.31G     0.2473     0.4712     0.1524         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.845      0.864      0.898      0.762

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     21/150      5.31G     0.2221     0.3514     0.1428         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     21/150      5.31G     0.2468      0.463     0.1528         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.869      0.889      0.908      0.783

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     22/150      5.31G     0.2627     0.3704       0.13         36        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     22/150      5.31G     0.2384     0.4583     0.1481         12        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.856      0.845      0.891      0.763

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     23/150      5.31G     0.3158     0.5348     0.1429         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     23/150      5.31G     0.2383     0.4598     0.1429         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660       0.89      0.875      0.918      0.792

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     24/150      5.31G     0.1524     0.3687    0.09394         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     24/150      5.31G     0.2353     0.4673     0.1392         27        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.87       0.88      0.899      0.767

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     25/150      5.31G     0.2341     0.4082     0.1845         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     25/150      5.31G     0.2349     0.4651     0.1467         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.875      0.837      0.898      0.776

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     26/150      5.31G     0.2715     0.5511     0.1185         48        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     26/150      5.31G     0.2314     0.4681     0.1401         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.863      0.865      0.909      0.783

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     27/150      5.31G     0.1889     0.4613    0.08651         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     27/150      5.31G     0.2295     0.4586     0.1389         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.87      0.854      0.906      0.786

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     28/150      5.31G     0.2588      0.543     0.1141         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     28/150      5.31G     0.2304     0.4386      0.143         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.901      0.885      0.931      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     29/150      5.31G     0.1706     0.5492    0.07453         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     29/150      5.31G     0.2135     0.4265     0.1312         31        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660       0.89      0.898      0.924      0.801

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     30/150      5.31G     0.2161     0.3569    0.09883         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     30/150      5.31G     0.2345     0.4449     0.1491         28        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.902      0.882      0.939       0.82

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     31/150      5.31G     0.3113     0.4864     0.1955         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     31/150      5.31G     0.2212     0.4366     0.1325         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.885      0.857      0.918      0.797

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     32/150      5.31G     0.1343     0.2777    0.07928         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     32/150      5.31G      0.226     0.4526     0.1372         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.892      0.826      0.909      0.788

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     33/150      5.31G     0.1771     0.5517     0.1351         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     33/150      5.31G      0.221     0.4364     0.1308          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660        0.9      0.902      0.933      0.814

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     34/150      5.31G     0.2063     0.4854     0.1472         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     34/150      5.31G     0.2224     0.4388     0.1342         14        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660        0.9      0.905      0.936       0.81

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     35/150      5.31G     0.2827     0.3277     0.1303         29        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     35/150      5.31G     0.2131     0.4045     0.1258         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.6it/s 2.4s
                   all        202        660        0.9      0.862      0.909      0.798

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     36/150      5.31G     0.1804     0.3972    0.07129         38        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     36/150      5.31G     0.2122     0.4159     0.1245         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660       0.89      0.873       0.93      0.818

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     37/150      5.31G     0.2123     0.3937    0.08298         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     37/150      5.31G     0.2076     0.4081     0.1242         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.897      0.876      0.926      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     38/150      5.31G      0.201     0.3773    0.09547         35        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     38/150      5.31G     0.2121     0.3992     0.1233         10        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.887      0.883      0.922      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     39/150      5.31G     0.3022     0.3523     0.1881         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     39/150      5.31G      0.218     0.4336     0.1288         13        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.891      0.859      0.901       0.78

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     40/150      5.31G     0.2277     0.5195     0.2376         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     40/150      5.31G     0.2113     0.4214     0.1277         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.894      0.883      0.924      0.795

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     41/150      5.31G     0.2715     0.4199     0.1294         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     41/150      5.31G     0.2107     0.4327      0.124         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.5it/s 2.5s
                   all        202        660      0.907      0.893      0.936      0.818

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     42/150      5.31G     0.2163     0.3732     0.1545         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     42/150      5.31G     0.2143     0.4087     0.1266         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.906      0.881      0.935      0.811

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     43/150      5.31G     0.2603     0.5481     0.1369         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     43/150      5.31G     0.2105     0.4084     0.1246         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.4it/s 2.3s
                   all        202        660      0.895      0.883      0.928      0.807

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     44/150      5.31G     0.1404      0.306    0.07142         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     44/150      5.31G     0.2104     0.4074     0.1268         12        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.896      0.828       0.89       0.78

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     45/150      5.31G     0.3026     0.7116     0.1993         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     45/150      5.31G     0.2014     0.3927     0.1206         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.895      0.885      0.928      0.816

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     46/150      5.31G     0.2235     0.4171     0.2789         12        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     46/150      5.31G     0.2047     0.3976     0.1263         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.907      0.884      0.936      0.827

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     47/150      5.31G     0.2479      0.496      0.138         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     47/150      5.31G      0.204     0.3838     0.1211         12        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.898      0.883      0.935      0.821

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     48/150      5.31G     0.1514     0.3865     0.1079         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     48/150      5.31G     0.2078     0.4225     0.1313         25        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.881      0.903      0.932      0.814

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     49/150      5.31G     0.2036     0.4044     0.1292         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     49/150      5.31G     0.2059     0.4106     0.1204          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.907      0.877      0.934      0.819

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     50/150      5.31G      0.238     0.3991     0.1384         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     50/150      5.31G     0.2015     0.3994     0.1222         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.875      0.892      0.922      0.812

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     51/150      5.31G     0.2266     0.4529      0.114         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     51/150      5.31G     0.2042      0.392     0.1214         13        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.894      0.873      0.913      0.807

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     52/150      5.31G     0.1564      0.417     0.1553         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     52/150      5.31G     0.1939     0.3797     0.1147         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.913      0.861      0.915      0.808

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     53/150      5.31G     0.1177     0.3364     0.0766         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     53/150      5.31G     0.1912     0.3775     0.1152         26        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.901       0.89      0.933      0.824

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     54/150      5.31G     0.1032     0.3995    0.05646         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     54/150      5.31G     0.1933     0.3755     0.1163          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.903      0.915      0.936      0.826

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     55/150      5.31G     0.2835      0.403     0.1375         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     55/150      5.31G     0.1971     0.3768     0.1156         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.894      0.902       0.93      0.822

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     56/150      5.31G     0.1663     0.2593     0.1062         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     56/150      5.31G     0.1972     0.3713     0.1167         33        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.894       0.91      0.935      0.818

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     57/150      5.31G     0.2358     0.3936     0.1546         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     57/150      5.31G     0.1884     0.3768     0.1117         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660        0.9      0.861       0.93      0.815

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     58/150      5.31G     0.1577      0.279    0.09529         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     58/150      5.31G     0.1914       0.39      0.114         13        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.907      0.879      0.933      0.817

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     59/150      5.31G     0.2372     0.3838     0.1359         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     59/150      5.31G     0.2009     0.3937     0.1222         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.885      0.877      0.925      0.809

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     60/150      5.31G     0.2018     0.3171     0.1079         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     60/150      5.31G     0.2055      0.414     0.1274         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.897      0.877      0.926      0.813

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     61/150      5.31G     0.1684     0.3161    0.09066         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     61/150      5.31G     0.2035     0.3963     0.1252         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.889      0.868      0.925      0.805

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     62/150      5.31G     0.1489     0.3411    0.08004         35        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     62/150      5.31G     0.2003     0.3889     0.1172         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 54.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.865      0.839      0.891      0.772

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     63/150      5.31G     0.2265     0.3864     0.1464         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     63/150      5.31G     0.1897     0.3884     0.1138         28        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.901      0.888      0.935      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     64/150      5.31G     0.1407     0.2472    0.07274         10        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     64/150      5.31G     0.1971     0.3901     0.1148         24        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.901      0.889      0.934      0.817

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     65/150      5.31G     0.1686     0.3678    0.07445         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     65/150      5.31G     0.1991     0.3843     0.1149         30        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660        0.9      0.895      0.931      0.826

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     66/150      5.31G     0.1949     0.3821      0.103         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     66/150      5.31G     0.1891     0.3614     0.1141         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.909      0.898      0.942      0.828

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     67/150      5.31G     0.2299     0.3477      0.126         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     67/150      5.31G      0.195     0.3781     0.1175         25        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.902       0.89      0.938      0.833

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     68/150      5.31G     0.1452       0.31     0.1024         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     68/150      5.31G     0.1947     0.3648     0.1123         14        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.888      0.912       0.94      0.837

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     69/150      5.31G     0.1392      0.347    0.07058         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     69/150      5.31G     0.1859      0.356     0.1116         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.921       0.91      0.948      0.839

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     70/150      5.31G       0.19     0.3358     0.1001         14        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     70/150      5.31G     0.1885     0.3666     0.1126          8        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.919      0.888      0.943      0.836

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     71/150      5.31G     0.2875     0.2954      0.149         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     71/150      5.31G     0.1907     0.3538     0.1116         11        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.894      0.923      0.943      0.834

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     72/150      5.31G    0.07626     0.1875    0.05583         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     72/150      5.31G     0.1911     0.3662     0.1135         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660       0.88      0.882      0.939      0.829

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     73/150      5.31G     0.2331     0.4072     0.2212         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     73/150      5.31G     0.1872      0.357     0.1104         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.913      0.898      0.932      0.828

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     74/150      5.31G     0.1698     0.2765    0.07729         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     74/150      5.31G     0.1805     0.3347     0.1065         27        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.913      0.896      0.934      0.828

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     75/150      5.31G     0.2105     0.3266    0.08509         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     75/150      5.31G     0.1765     0.3312      0.107          9        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.886      0.891      0.931      0.823

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     76/150      5.31G     0.2335     0.3946     0.1736         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     76/150      5.31G     0.1784      0.339     0.1033         24        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.907       0.91      0.944      0.838

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     77/150      5.31G     0.2052     0.3616    0.08824         36        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     77/150      5.31G     0.1771      0.339     0.1028         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.892      0.909      0.946      0.836

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     78/150      5.31G     0.1785     0.3199     0.1084         28        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     78/150      5.31G     0.1757     0.3399     0.1026         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.915       0.91      0.954      0.851

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     79/150      5.31G     0.2074     0.4346     0.1706         11        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     79/150      5.31G     0.1784     0.3399     0.1065         28        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.911      0.916      0.948      0.841

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     80/150      5.31G     0.1755     0.3786     0.1389         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     80/150      5.31G     0.1783     0.3291     0.1068         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660       0.91      0.911      0.948      0.843

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     81/150      5.31G     0.1144     0.2419    0.08616         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     81/150      5.31G     0.1743     0.3359     0.1015         30        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.929      0.905      0.948      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     82/150      5.31G     0.2104     0.3386    0.09928         27        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     82/150      5.31G      0.168     0.3229    0.09753         21        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.926      0.902       0.94      0.837

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     83/150      5.31G     0.1018     0.2196    0.07159         15        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     83/150      5.31G     0.1652     0.3259    0.09765         19        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.905      0.913      0.941       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     84/150      5.31G     0.1793     0.4036    0.09708         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     84/150      5.31G     0.1704     0.3245    0.09878         26        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.911      0.904      0.943      0.844

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     85/150      5.31G      0.292     0.3103     0.1203         26        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     85/150      5.31G     0.1793     0.3224     0.1037         13        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.894       0.92      0.951      0.843

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     86/150      5.31G     0.1264     0.3454    0.07389         40        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     86/150      5.31G     0.1622     0.3233    0.09537         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.927      0.886      0.945      0.844

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     87/150      5.31G     0.1369     0.2902    0.07082         34        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     87/150      5.31G     0.1748     0.3272     0.1023         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.913      0.922      0.953      0.854

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     88/150      5.31G     0.1942     0.3423     0.1311         34        512: 0% ──────────── 0/177  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     88/150      5.31G     0.1722     0.3284    0.09801         12        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.917      0.912      0.949      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     89/150      5.31G     0.1848     0.2569    0.09475         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     89/150      5.31G     0.1655     0.3198    0.09758         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.917      0.916      0.946      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     90/150      5.31G     0.1621     0.3229     0.1443         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     90/150      5.31G     0.1578     0.3069    0.09151         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.917       0.91      0.948      0.842

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     91/150      5.31G     0.1488     0.3825     0.1449         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     91/150      5.31G     0.1594      0.306    0.09244         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.894      0.929      0.954      0.847

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     92/150      5.31G     0.1605     0.3049     0.1068         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     92/150      5.31G     0.1608      0.304    0.09321         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.916       0.91      0.952      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     93/150      5.31G     0.1595     0.3045    0.09262         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     93/150      5.31G     0.1632     0.2987    0.09134         13        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.915       0.92       0.95      0.847

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     94/150      5.31G     0.2159     0.3155      0.145         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     94/150      5.31G     0.1584     0.2964    0.08875         24        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.933      0.917      0.954      0.855

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     95/150      5.31G     0.1066     0.2186    0.08912         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     95/150      5.31G     0.1566     0.2917    0.08684          7        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.923      0.909      0.945      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     96/150      5.31G     0.1379     0.3111     0.0877         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     96/150      5.31G     0.1603      0.304    0.09087         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.908      0.924      0.941      0.841

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     97/150      5.31G     0.1754     0.3227    0.09594         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     97/150      5.31G      0.151     0.2997    0.09044         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.918      0.899      0.945      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     98/150      5.31G      0.129     0.2474    0.05236         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     98/150      5.31G     0.1593     0.3017    0.09296         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.5it/s 2.5s
                   all        202        660      0.905      0.925      0.945       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
     99/150      5.31G      0.123     0.2428     0.0649         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

     99/150      5.31G     0.1552     0.2979    0.08849         20        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.909       0.91      0.947      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    100/150      5.31G    0.09305     0.1873    0.06145         24        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    100/150      5.31G     0.1511     0.2986    0.08888         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.928      0.909      0.948      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    101/150      5.31G      0.168     0.3142    0.07219         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    101/150      5.31G     0.1547     0.2906    0.08676         27        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.913      0.918      0.951       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    102/150      5.31G     0.1155     0.2204    0.09636         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    102/150      5.31G     0.1586     0.2904    0.09008         10        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.923      0.897      0.943       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    103/150      5.31G     0.2539     0.2991    0.06271         25        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    103/150      5.31G     0.1626     0.3087    0.09475         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.925      0.908      0.943       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    104/150      5.31G     0.1153      0.263     0.0952         17        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    104/150      5.31G     0.1559     0.3008    0.08691         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.915      0.914      0.949       0.85

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    105/150      5.31G     0.1697     0.2464    0.08593         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    105/150      5.31G     0.1471     0.2814     0.0826         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.911      0.908      0.947      0.848

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    106/150      5.31G     0.2006     0.3267     0.1159         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    106/150      5.31G     0.1506     0.2879    0.08341         15        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.922       0.91      0.953      0.858

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    107/150      5.31G     0.1135     0.2694    0.08852         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    107/150      5.31G     0.1477     0.2855     0.0867         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.918      0.902      0.946      0.844

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    108/150      5.31G     0.1968     0.4683     0.1209         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    108/150      5.31G     0.1479      0.287    0.08505         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.927      0.909      0.949      0.851

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    109/150      5.31G     0.1338     0.2546    0.07199         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    109/150      5.31G     0.1543     0.2968    0.08636         23        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.926      0.912      0.949      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    110/150      5.31G     0.1101     0.2315    0.07848         13        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    110/150      5.31G     0.1482     0.2938    0.08459         30        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.3s
                   all        202        660      0.901      0.922      0.943       0.84

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    111/150      5.31G     0.1082     0.2428    0.05704         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    111/150      5.31G     0.1519     0.2834    0.08609         14        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.913      0.906      0.944      0.847

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    112/150      5.31G    0.08915     0.1793    0.06859         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    112/150      5.31G     0.1496     0.2804    0.08277         29        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.926      0.895      0.949      0.847

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    113/150      5.31G     0.1153     0.2326    0.08192         33        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    113/150      5.31G     0.1451     0.2802    0.08174         25        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.902      0.919      0.945      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    114/150      5.31G     0.1417     0.2816     0.1055         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    114/150      5.31G     0.1483     0.2824    0.08423         33        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.911       0.91      0.949      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    115/150      5.31G     0.1601     0.2153    0.07323         31        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    115/150      5.31G     0.1421     0.2797    0.08273         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.904      0.909      0.933      0.833

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    116/150      5.31G    0.07172     0.2097    0.04837         21        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    116/150      5.31G     0.1462     0.2794    0.08222         18        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.914      0.904      0.942      0.844

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    117/150      5.31G     0.1486      0.327    0.06625         30        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    117/150      5.31G     0.1463     0.2697    0.08158         22        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.3it/s 2.3s
                   all        202        660      0.916      0.892      0.943      0.846

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    118/150      5.31G     0.1024     0.2664    0.08086         20        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    118/150      5.31G     0.1435     0.2687    0.08382         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.905      0.915      0.942      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    119/150      5.31G    0.08654     0.2465    0.04391         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    119/150      5.31G     0.1485     0.2744    0.08308         25        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.904      0.912      0.945      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    120/150      5.31G    0.09988      0.217     0.0528         14        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    120/150      5.31G     0.1439     0.2609    0.08247         17        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.914      0.895      0.941      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    121/150      5.31G     0.1435     0.2602    0.09922         16        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    121/150      5.31G     0.1442      0.261    0.08239         30        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.911      0.916      0.945      0.848

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    122/150      5.31G     0.1427     0.2149    0.07331         15        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    122/150      5.31G     0.1417     0.2655    0.08048         30        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.1it/s 2.4s
                   all        202        660      0.918      0.911      0.946      0.849

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    123/150      5.31G     0.2532     0.2427    0.07561         23        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    123/150      5.31G     0.1397     0.2614    0.07817         14        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.2it/s 2.3s
                   all        202        660      0.895      0.917      0.944      0.848

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    124/150      5.31G     0.1592     0.2462    0.09425         22        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    124/150      5.31G     0.1416     0.2566    0.07834         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.7it/s 2.4s
                   all        202        660      0.908      0.898       0.94      0.842

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    125/150      5.31G    0.07517     0.3095    0.04558         19        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    125/150      5.31G     0.1379     0.2614    0.07903         16        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.8it/s 2.4s
                   all        202        660      0.919      0.904      0.939      0.845

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
    126/150      5.31G     0.1709     0.2954     0.0436         18        512: 0% ──────────── 0/177  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

    126/150      5.31G     0.1373     0.2628    0.07917         29        512: 100% ━━━━━━━━━━━━ 177/177 3.3it/s 53.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 11.0it/s 2.4s
                   all        202        660      0.902      0.917      0.943      0.848
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 106, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

126 epochs completed in 2.007 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2/weights/last.pt, 66.2MB
Optimizer stripped from /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2/weights/best.pt, 66.2MB

Validating /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2/weights/best.pt...
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 10.9it/s 2.4s
                   all        202        660      0.921      0.909      0.953      0.858
                     0        187        321      0.912      0.903      0.947      0.846
                     1        188        339      0.929      0.914      0.959       0.87
Speed: 0.1ms preprocess, 7.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp/runs_detection_models/rtdetr_l_seed2
Ultralytics 8.4.104 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1096.2±265.8 MB/s, size: 29.4 KB)
val: Scanning /content/data/data/tom_benh.v1i.yolov11/test/labels.cache... 101 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 101/101 35.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 26/26 14.6it/s 1.8s
                   all        101        320      0.885      0.866      0.913      0.795
Speed: 1.1ms preprocess, 11.5ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /content/runs/detect/val-3

,model,seed,run,best_epoch,best_val_mAP50-95,precision,recall,mAP50,mAP50-95,preprocess_ms,inference_ms,postprocess_ms
0,RT-DETR-L,0,rtdetr_l_seed0,NaN,NaN,0.882541,0.875722,0.911389,0.800865,0.522928,12.085252,0.196965
1,RT-DETR-L,1,rtdetr_l_seed1,NaN,NaN,0.861996,0.842680,0.880085,0.759624,0.558458,11.779083,0.202699
2,RT-DETR-L,2,rtdetr_l_seed2,NaN,NaN,0.885382,0.865639,0.912915,0.794719,1.141763,11.526405,0.207628

## Save Detection-Model Summary

In [17]:
all_detection_rows = []
for name in ['faster_rcnn_rows', 'efficientdet_rows', 'rtdetr_rows']:
    all_detection_rows.extend(globals().get(name, []))

detection_runs_df, detection_summary_df = summarize_results(all_detection_rows, OUTPUT_ROOT)

per-run saved: /content/drive/MyDrive/shrimp/runs_detection_models/detection_models_test_summary_per_run.csv
summary saved: /content/drive/MyDrive/shrimp/runs_detection_models/detection_models_test_summary_mean_std.csv

,model,seed,run,best_epoch,best_val_mAP50-95,precision,recall,mAP50,mAP50-95,inference_ms,preprocess_ms,postprocess_ms
0,Faster R-CNN ResNet50 FPN v2,0,fasterrcnn_resnet50_fpn_v2_seed0,56.0,0.760215,0.564639,0.928125,0.874963,0.707457,16.991587,NaN,NaN
1,Faster R-CNN ResNet50 FPN v2,1,fasterrcnn_resnet50_fpn_v2_seed1,51.0,0.766708,0.610063,0.909375,0.860846,0.691223,13.431556,NaN,NaN
2,Faster R-CNN ResNet50 FPN v2,2,fasterrcnn_resnet50_fpn_v2_seed2,83.0,0.769670,0.601240,0.909375,0.858685,0.690967,13.811558,NaN,NaN
3,EfficientDet-D0,0,efficientdet_d0_seed0,100.0,0.731596,0.030990,0.978125,0.900497,0.692968,15.882019,NaN,NaN
4,EfficientDet-D0,1,efficientdet_d0_seed1,69.0,0.720706,0.030891,0.975000,0.888401,0.671769,10.755861,NaN,NaN
5,EfficientDet-D0,2,efficientdet_d0_seed2,63.0,0.721444,0.030891,0.975000,0.898287,0.690050,10.882426,NaN,NaN
6,RT-DETR-L,0,rtdetr_l_seed0,NaN,NaN,0.882541,0.875722,0.911389,0.800865,12.085252,0.522928,0.196965
7,RT-DETR-L,1,rtdetr_l_seed1,NaN,NaN,0.861996,0.842680,0.880085,0.759624,11.779083,0.558458,0.202699
8,RT-DETR-L,2,rtdetr_l_seed2,NaN,NaN,0.885382,0.865639,0.912915,0.794719,11.526405,1.141763,0.207628

,model,precision_mean,precision_std,recall_mean,recall_std,mAP50_mean,mAP50_std,mAP50-95_mean,mAP50-95_std,inference_ms_mean,inference_ms_std,best_epoch_mean,best_epoch_std,best_val_mAP50-95_mean,best_val_mAP50-95_std
0,EfficientDet-D0,0.030924,0.000057,0.976042,0.001804,0.895728,0.006441,0.684929,0.011490,12.506769,2.923737,77.333333,19.857828,0.724582,0.006085
1,Faster R-CNN ResNet50 FPN v2,0.591980,0.024086,0.915625,0.010825,0.864831,0.008840,0.696549,0.009447,14.744900,1.954942,63.333333,17.214335,0.765531,0.004836
2,RT-DETR-L,0.876640,0.012761,0.861347,0.016934,0.901463,0.018530,0.785069,0.022250,11.796913,0.279850,NaN,NaN,NaN,NaN

## Optional: Combine With Existing YOLO Summary

In [18]:
if YOLO_SUMMARY_PER_RUN.exists():
    yolo_df = pd.read_csv(YOLO_SUMMARY_PER_RUN)
    detection_df = pd.read_csv(OUTPUT_ROOT / 'detection_models_test_summary_per_run.csv')
    common_cols = sorted(set(yolo_df.columns).union(detection_df.columns))
    combined = pd.concat([
        yolo_df.reindex(columns=common_cols),
        detection_df.reindex(columns=common_cols),
    ], ignore_index=True)

    combined_path = OUTPUT_ROOT / 'all_models_test_summary_per_run.csv'
    combined_summary_path = OUTPUT_ROOT / 'all_models_test_summary_mean_std.csv'
    combined.to_csv(combined_path, index=False)

    metric_cols = [
        'precision', 'recall', 'mAP50', 'mAP50-95',
        'preprocess_ms', 'inference_ms', 'postprocess_ms',
        'best_epoch', 'best_val_mAP50-95'
    ]
    metric_cols = [c for c in metric_cols if c in combined.columns]
    combined_summary = combined.groupby('model')[metric_cols].agg(['mean', 'std'])
    combined_summary.columns = [f'{col}_{stat}' for col, stat in combined_summary.columns]
    combined_summary = combined_summary.reset_index()
    combined_summary.to_csv(combined_summary_path, index=False)

    print('combined per-run saved:', combined_path)
    print('combined summary saved:', combined_summary_path)
    display(combined)
    display(combined_summary)
else:
    print('YOLO summary not found:', YOLO_SUMMARY_PER_RUN)
    print('Run the evaluation cell in shrimp.ipynb first if you want one combined table.')

YOLO summary not found: /content/drive/MyDrive/shrimp/test_summary_per_run.csv
Run the evaluation cell in shrimp.ipynb first if you want one combined table.

## Notes

- For the most defensible comparison, use the same Roboflow version for both `/content/shrimp-yolo` and `/content/shrimp-coco`.
- Faster R-CNN and EfficientDet use a YOLO-style letterbox resize so the input geometry is closer to Ultralytics validation at `imgsz=512`.
- Faster R-CNN and EfficientDet checkpoints are selected by validation `mAP50-95`; test results are computed only after selection.
- `BATCH_SIZE=4` with gradient accumulation is used to approximate YOLO's effective batch size of 32 on Colab GPUs. If your GPU can fit a larger batch, increase `BATCH_SIZE` and keep `EFFECTIVE_BATCH_SIZE=32`.
- If a model runs out of VRAM, reduce `BATCH_SIZE` to `2` or `1`; report that setting with the results.

In [19]:
from google.colab import runtime

print("Archive saved. Disconnecting runtime...")
runtime.unassign()

Archive saved. Disconnecting runtime...